//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from AnnouncementStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class AnnouncementStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.AnnouncementStrings", typeof(AnnouncementStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string ApiBaseUrl => ResourceManager.GetString(nameof(ApiBaseUrl), _resourceCulture);

        public static string ApiBaseUrlHint => ResourceManager.GetString(nameof(ApiBaseUrlHint), _resourceCulture);

        public static string CenterHint => ResourceManager.GetString(nameof(CenterHint), _resourceCulture);

        public static string CenterTitle => ResourceManager.GetString(nameof(CenterTitle), _resourceCulture);

        public static string ClearHistory => ResourceManager.GetString(nameof(ClearHistory), _resourceCulture);

        public static string ConnectionHint => ResourceManager.GetString(nameof(ConnectionHint), _resourceCulture);

        public static string ConnectionTitle => ResourceManager.GetString(nameof(ConnectionTitle), _resourceCulture);

        public static string ItemCount => ResourceManager.GetString(nameof(ItemCount), _resourceCulture);

        public static string MarkAllAsRead => ResourceManager.GetString(nameof(MarkAllAsRead), _resourceCulture);

        public static string NavTooltip => ResourceManager.GetString(nameof(NavTooltip), _resourceCulture);

        public static string NoItems => ResourceManager.GetString(nameof(NoItems), _resourceCulture);

        public static string PageTitle => ResourceManager.GetString(nameof(PageTitle), _resourceCulture);

        public static string Token => ResourceManager.GetString(nameof(Token), _resourceCulture);

        public static string TokenHint => ResourceManager.GetString(nameof(TokenHint), _resourceCulture);

        public static string WebSocketUrl => ResourceManager.GetString(nameof(WebSocketUrl), _resourceCulture);

        public static string WebSocketUrlHint => ResourceManager.GetString(nameof(WebSocketUrlHint), _resourceCulture);
    }
}