//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from AutomationStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class AutomationStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.AutomationStrings", typeof(AutomationStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AutoFold_App_AdmoxBoard => ResourceManager.GetString(nameof(AutoFold_App_AdmoxBoard), _resourceCulture);

        public static string AutoFold_App_AdmoxBooth => ResourceManager.GetString(nameof(AutoFold_App_AdmoxBooth), _resourceCulture);

        public static string AutoFold_App_HiteBoard => ResourceManager.GetString(nameof(AutoFold_App_HiteBoard), _resourceCulture);

        public static string AutoFold_App_HiteCamera => ResourceManager.GetString(nameof(AutoFold_App_HiteCamera), _resourceCulture);

        public static string AutoFold_App_HiteLightBoard => ResourceManager.GetString(nameof(AutoFold_App_HiteLightBoard), _resourceCulture);

        public static string AutoFold_App_MaxHubBoard => ResourceManager.GetString(nameof(AutoFold_App_MaxHubBoard), _resourceCulture);

        public static string AutoFold_App_MSWhiteboard => ResourceManager.GetString(nameof(AutoFold_App_MSWhiteboard), _resourceCulture);

        public static string AutoFold_App_SeewoBoard3 => ResourceManager.GetString(nameof(AutoFold_App_SeewoBoard3), _resourceCulture);

        public static string AutoFold_App_SeewoBoard5 => ResourceManager.GetString(nameof(AutoFold_App_SeewoBoard5), _resourceCulture);

        public static string AutoFold_App_SeewoCamera => ResourceManager.GetString(nameof(AutoFold_App_SeewoCamera), _resourceCulture);

        public static string AutoFold_App_SeewoLightBoard => ResourceManager.GetString(nameof(AutoFold_App_SeewoLightBoard), _resourceCulture);

        public static string AutoFold_App_SeewoLightBoard5C => ResourceManager.GetString(nameof(AutoFold_App_SeewoLightBoard5C), _resourceCulture);

        public static string AutoFold_App_WenXiangBoard => ResourceManager.GetString(nameof(AutoFold_App_WenXiangBoard), _resourceCulture);

        public static string AutoFold_App_YiYunBoard => ResourceManager.GetString(nameof(AutoFold_App_YiYunBoard), _resourceCulture);

        public static string AutoFold_App_YiYunBooth => ResourceManager.GetString(nameof(AutoFold_App_YiYunBooth), _resourceCulture);

        public static string AutoFold_Mode => ResourceManager.GetString(nameof(AutoFold_Mode), _resourceCulture);

        public static string AutoFold_OldZyBoard => ResourceManager.GetString(nameof(AutoFold_OldZyBoard), _resourceCulture);

        public static string AutoKill_EasiNote5 => ResourceManager.GetString(nameof(AutoKill_EasiNote5), _resourceCulture);

        public static string AutoKill_HiteAfterKillEnterAnnotation => ResourceManager.GetString(nameof(AutoKill_HiteAfterKillEnterAnnotation), _resourceCulture);

        public static string AutoKill_HiteAnnotation => ResourceManager.GetString(nameof(AutoKill_HiteAnnotation), _resourceCulture);

        public static string AutoKill_ICA => ResourceManager.GetString(nameof(AutoKill_ICA), _resourceCulture);

        public static string AutoKill_InkCanvasIC => ResourceManager.GetString(nameof(AutoKill_InkCanvasIC), _resourceCulture);

        public static string AutoKill_Inkeys => ResourceManager.GetString(nameof(AutoKill_Inkeys), _resourceCulture);

        public static string AutoKill_PPTTools => ResourceManager.GetString(nameof(AutoKill_PPTTools), _resourceCulture);

        public static string AutoKill_PPTToolsHint => ResourceManager.GetString(nameof(AutoKill_PPTToolsHint), _resourceCulture);

        public static string AutoKill_SeewoDesktop2Anno => ResourceManager.GetString(nameof(AutoKill_SeewoDesktop2Anno), _resourceCulture);

        public static string AutoKill_SeewoDesktop2AnnoHint => ResourceManager.GetString(nameof(AutoKill_SeewoDesktop2AnnoHint), _resourceCulture);

        public static string AutoKill_Title => ResourceManager.GetString(nameof(AutoKill_Title), _resourceCulture);

        public static string AutoKill_YouJiao => ResourceManager.GetString(nameof(AutoKill_YouJiao), _resourceCulture);

        public static string Automation_AutoFoldInPPT => ResourceManager.GetString(nameof(Automation_AutoFoldInPPT), _resourceCulture);

        public static string Automation_AutoFoldTitle => ResourceManager.GetString(nameof(Automation_AutoFoldTitle), _resourceCulture);

        public static string Automation_KeepFoldAfterExit => ResourceManager.GetString(nameof(Automation_KeepFoldAfterExit), _resourceCulture);

        public static string Automation_KeepFoldAfterExitHint => ResourceManager.GetString(nameof(Automation_KeepFoldAfterExitHint), _resourceCulture);

        public static string Automation_SaveFileName_Custom => ResourceManager.GetString(nameof(Automation_SaveFileName_Custom), _resourceCulture);

        public static string Automation_SaveFileName_CustomTemplate_Desc => ResourceManager.GetString(nameof(Automation_SaveFileName_CustomTemplate_Desc), _resourceCulture);

        public static string Automation_SaveFileName_CustomTemplate_Header => ResourceManager.GetString(nameof(Automation_SaveFileName_CustomTemplate_Header), _resourceCulture);

        public static string Automation_SaveFileName_Date => ResourceManager.GetString(nameof(Automation_SaveFileName_Date), _resourceCulture);

        public static string Automation_SaveFileName_DateMode => ResourceManager.GetString(nameof(Automation_SaveFileName_DateMode), _resourceCulture);

        public static string Automation_SaveFileName_DateModePage => ResourceManager.GetString(nameof(Automation_SaveFileName_DateModePage), _resourceCulture);

        public static string Automation_SaveFileName_DateModePageCount => ResourceManager.GetString(nameof(Automation_SaveFileName_DateModePageCount), _resourceCulture);

        public static string Automation_SaveFileName_DateTime => ResourceManager.GetString(nameof(Automation_SaveFileName_DateTime), _resourceCulture);

        public static string Automation_SaveFileName_Timestamp => ResourceManager.GetString(nameof(Automation_SaveFileName_Timestamp), _resourceCulture);

        public static string Automation_SaveFileNameFormat => ResourceManager.GetString(nameof(Automation_SaveFileNameFormat), _resourceCulture);

        public static string Automation_Title => ResourceManager.GetString(nameof(Automation_Title), _resourceCulture);

        public static string Automation_UseCustomSaveFileName_Desc => ResourceManager.GetString(nameof(Automation_UseCustomSaveFileName_Desc), _resourceCulture);

        public static string Automation_UseCustomSaveFileName_Header => ResourceManager.GetString(nameof(Automation_UseCustomSaveFileName_Header), _resourceCulture);

        public static string FloatingInterceptor_App_ChangYanClass => ResourceManager.GetString(nameof(FloatingInterceptor_App_ChangYanClass), _resourceCulture);

        public static string FloatingInterceptor_App_ChangYanPPT => ResourceManager.GetString(nameof(FloatingInterceptor_App_ChangYanPPT), _resourceCulture);

        public static string FloatingInterceptor_App_HiteAnnotation => ResourceManager.GetString(nameof(FloatingInterceptor_App_HiteAnnotation), _resourceCulture);

        public static string FloatingInterceptor_App_IntelligentClass => ResourceManager.GetString(nameof(FloatingInterceptor_App_IntelligentClass), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoBoard5C => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoBoard5C), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoDesktopAnnotation => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoDesktopAnnotation), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoDesktopSideBar => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoDesktopSideBar), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoPinco => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoPinco), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoPincoDrawing => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoPincoDrawing), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoPPTTools => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoPPTTools), _resourceCulture);

        public static string FloatingInterceptor_Enable => ResourceManager.GetString(nameof(FloatingInterceptor_Enable), _resourceCulture);

        public static string FloatingInterceptor_Title => ResourceManager.GetString(nameof(FloatingInterceptor_Title), _resourceCulture);

        public static string FoldMode_AutoFoldAfterPPT => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterPPT), _resourceCulture);

        public static string FoldMode_AutoFoldAfterPPTHint => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterPPTHint), _resourceCulture);

        public static string FoldMode_AutoFoldAfterWhiteboard => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterWhiteboard), _resourceCulture);

        public static string FoldMode_AutoFoldAfterWhiteboardHint => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterWhiteboardHint), _resourceCulture);

        public static string FoldMode_ExitToAnnotation => ResourceManager.GetString(nameof(FoldMode_ExitToAnnotation), _resourceCulture);

        public static string FoldMode_ExitToAnnotationHint => ResourceManager.GetString(nameof(FoldMode_ExitToAnnotationHint), _resourceCulture);

        public static string AutoFold_Group_Seewo => ResourceManager.GetString(nameof(AutoFold_Group_Seewo), _resourceCulture);

        public static string AutoFold_Group_Hite => ResourceManager.GetString(nameof(AutoFold_Group_Hite), _resourceCulture);

        public static string AutoFold_Group_Other => ResourceManager.GetString(nameof(AutoFold_Group_Other), _resourceCulture);

        public static string FloatingInterceptor_Group_Seewo => ResourceManager.GetString(nameof(FloatingInterceptor_Group_Seewo), _resourceCulture);

        public static string FileAssoc_CheckDesc => ResourceManager.GetString(nameof(FileAssoc_CheckDesc), _resourceCulture);

        public static string FileAssoc_RegisterHeader => ResourceManager.GetString(nameof(FileAssoc_RegisterHeader), _resourceCulture);

        public static string FileAssoc_RegisterDesc => ResourceManager.GetString(nameof(FileAssoc_RegisterDesc), _resourceCulture);

        public static string FileAssoc_UnregisterDesc => ResourceManager.GetString(nameof(FileAssoc_UnregisterDesc), _resourceCulture);

        public static string FileAssoc_NotChecked => ResourceManager.GetString(nameof(FileAssoc_NotChecked), _resourceCulture);

        public static string FileAssoc_RegisterSuccess => ResourceManager.GetString(nameof(FileAssoc_RegisterSuccess), _resourceCulture);

        public static string FileAssoc_RegisterFailed => ResourceManager.GetString(nameof(FileAssoc_RegisterFailed), _resourceCulture);

        public static string FileAssoc_UnregisterSuccess => ResourceManager.GetString(nameof(FileAssoc_UnregisterSuccess), _resourceCulture);

        public static string FileAssoc_UnregisterFailed => ResourceManager.GetString(nameof(FileAssoc_UnregisterFailed), _resourceCulture);

        public static string FileAssoc_Registered => ResourceManager.GetString(nameof(FileAssoc_Registered), _resourceCulture);

        public static string FileAssoc_NotRegistered => ResourceManager.GetString(nameof(FileAssoc_NotRegistered), _resourceCulture);

        public static string FileAssoc_CheckError => ResourceManager.GetString(nameof(FileAssoc_CheckError), _resourceCulture);

        public static string Storage_AutoDeleteDaysThreshold => ResourceManager.GetString(nameof(Storage_AutoDeleteDaysThreshold), _resourceCulture);

        public static string Storage_MinAutomationStrokes => ResourceManager.GetString(nameof(Storage_MinAutomationStrokes), _resourceCulture);

        public static string FileAssoc_LoadedStrokesFile => ResourceManager.GetString(nameof(FileAssoc_LoadedStrokesFile), _resourceCulture);

        public static string FileAssoc_SwitchedToBoardMode => ResourceManager.GetString(nameof(FileAssoc_SwitchedToBoardMode), _resourceCulture);

        public static string FileAssoc_ExitedFoldMode => ResourceManager.GetString(nameof(FileAssoc_ExitedFoldMode), _resourceCulture);
    }
}