//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from AutomationStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class AutomationStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.AutomationStrings", typeof(AutomationStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AutoFold_App_AdmoxBoard => ResourceManager.GetString(nameof(AutoFold_App_AdmoxBoard), _resourceCulture);

        public static string AutoFold_App_AdmoxBooth => ResourceManager.GetString(nameof(AutoFold_App_AdmoxBooth), _resourceCulture);

        public static string AutoFold_App_HiteBoard => ResourceManager.GetString(nameof(AutoFold_App_HiteBoard), _resourceCulture);

        public static string AutoFold_App_HiteCamera => ResourceManager.GetString(nameof(AutoFold_App_HiteCamera), _resourceCulture);

        public static string AutoFold_App_HiteLightBoard => ResourceManager.GetString(nameof(AutoFold_App_HiteLightBoard), _resourceCulture);

        public static string AutoFold_App_MaxHubBoard => ResourceManager.GetString(nameof(AutoFold_App_MaxHubBoard), _resourceCulture);

        public static string AutoFold_App_MSWhiteboard => ResourceManager.GetString(nameof(AutoFold_App_MSWhiteboard), _resourceCulture);

        public static string AutoFold_App_SeewoBoard3 => ResourceManager.GetString(nameof(AutoFold_App_SeewoBoard3), _resourceCulture);

        public static string AutoFold_App_SeewoBoard5 => ResourceManager.GetString(nameof(AutoFold_App_SeewoBoard5), _resourceCulture);

        public static string AutoFold_App_SeewoCamera => ResourceManager.GetString(nameof(AutoFold_App_SeewoCamera), _resourceCulture);

        public static string AutoFold_App_SeewoLightBoard => ResourceManager.GetString(nameof(AutoFold_App_SeewoLightBoard), _resourceCulture);

        public static string AutoFold_App_SeewoLightBoard5C => ResourceManager.GetString(nameof(AutoFold_App_SeewoLightBoard5C), _resourceCulture);

        public static string AutoFold_App_WenXiangBoard => ResourceManager.GetString(nameof(AutoFold_App_WenXiangBoard), _resourceCulture);

        public static string AutoFold_App_YiYunBoard => ResourceManager.GetString(nameof(AutoFold_App_YiYunBoard), _resourceCulture);

        public static string AutoFold_App_YiYunBooth => ResourceManager.GetString(nameof(AutoFold_App_YiYunBooth), _resourceCulture);

        public static string AutoFold_Mode => ResourceManager.GetString(nameof(AutoFold_Mode), _resourceCulture);

        public static string AutoFold_OldZyBoard => ResourceManager.GetString(nameof(AutoFold_OldZyBoard), _resourceCulture);

        public static string AutoKill_EasiNote5 => ResourceManager.GetString(nameof(AutoKill_EasiNote5), _resourceCulture);

        public static string AutoKill_HiteAfterKillEnterAnnotation => ResourceManager.GetString(nameof(AutoKill_HiteAfterKillEnterAnnotation), _resourceCulture);

        public static string AutoKill_HiteAnnotation => ResourceManager.GetString(nameof(AutoKill_HiteAnnotation), _resourceCulture);

        public static string AutoKill_ICA => ResourceManager.GetString(nameof(AutoKill_ICA), _resourceCulture);

        public static string AutoKill_InkCanvasIC => ResourceManager.GetString(nameof(AutoKill_InkCanvasIC), _resourceCulture);

        public static string AutoKill_Inkeys => ResourceManager.GetString(nameof(AutoKill_Inkeys), _resourceCulture);

        public static string AutoKill_PPTTools => ResourceManager.GetString(nameof(AutoKill_PPTTools), _resourceCulture);

        public static string AutoKill_PPTToolsHint => ResourceManager.GetString(nameof(AutoKill_PPTToolsHint), _resourceCulture);

        public static string AutoKill_SeewoDesktop2Anno => ResourceManager.GetString(nameof(AutoKill_SeewoDesktop2Anno), _resourceCulture);

        public static string AutoKill_SeewoDesktop2AnnoHint => ResourceManager.GetString(nameof(AutoKill_SeewoDesktop2AnnoHint), _resourceCulture);

        public static string AutoKill_Title => ResourceManager.GetString(nameof(AutoKill_Title), _resourceCulture);

        public static string AutoKill_YouJiao => ResourceManager.GetString(nameof(AutoKill_YouJiao), _resourceCulture);

        public static string Automation_AutoFoldInPPT => ResourceManager.GetString(nameof(Automation_AutoFoldInPPT), _resourceCulture);

        public static string Automation_AutoFoldTitle => ResourceManager.GetString(nameof(Automation_AutoFoldTitle), _resourceCulture);

        public static string Automation_KeepFoldAfterExit => ResourceManager.GetString(nameof(Automation_KeepFoldAfterExit), _resourceCulture);

        public static string Automation_KeepFoldAfterExitHint => ResourceManager.GetString(nameof(Automation_KeepFoldAfterExitHint), _resourceCulture);

        public static string Automation_SaveFileName_Custom => ResourceManager.GetString(nameof(Automation_SaveFileName_Custom), _resourceCulture);

        public static string Automation_SaveFileName_CustomTemplate_Desc => ResourceManager.GetString(nameof(Automation_SaveFileName_CustomTemplate_Desc), _resourceCulture);

        public static string Automation_SaveFileName_CustomTemplate_Header => ResourceManager.GetString(nameof(Automation_SaveFileName_CustomTemplate_Header), _resourceCulture);

        public static string Automation_SaveFileName_Date => ResourceManager.GetString(nameof(Automation_SaveFileName_Date), _resourceCulture);

        public static string Automation_SaveFileName_DateMode => ResourceManager.GetString(nameof(Automation_SaveFileName_DateMode), _resourceCulture);

        public static string Automation_SaveFileName_DateModePage => ResourceManager.GetString(nameof(Automation_SaveFileName_DateModePage), _resourceCulture);

        public static string Automation_SaveFileName_DateModePageCount => ResourceManager.GetString(nameof(Automation_SaveFileName_DateModePageCount), _resourceCulture);

        public static string Automation_SaveFileName_DateTime => ResourceManager.GetString(nameof(Automation_SaveFileName_DateTime), _resourceCulture);

        public static string Automation_SaveFileName_Timestamp => ResourceManager.GetString(nameof(Automation_SaveFileName_Timestamp), _resourceCulture);

        public static string Automation_SaveFileNameFormat => ResourceManager.GetString(nameof(Automation_SaveFileNameFormat), _resourceCulture);

        public static string Automation_Title => ResourceManager.GetString(nameof(Automation_Title), _resourceCulture);

        public static string Automation_UseCustomSaveFileName_Desc => ResourceManager.GetString(nameof(Automation_UseCustomSaveFileName_Desc), _resourceCulture);

        public static string Automation_UseCustomSaveFileName_Header => ResourceManager.GetString(nameof(Automation_UseCustomSaveFileName_Header), _resourceCulture);

        public static string FloatingInterceptor_App_ChangYanClass => ResourceManager.GetString(nameof(FloatingInterceptor_App_ChangYanClass), _resourceCulture);

        public static string FloatingInterceptor_App_ChangYanPPT => ResourceManager.GetString(nameof(FloatingInterceptor_App_ChangYanPPT), _resourceCulture);

        public static string FloatingInterceptor_App_HiteAnnotation => ResourceManager.GetString(nameof(FloatingInterceptor_App_HiteAnnotation), _resourceCulture);

        public static string FloatingInterceptor_App_IntelligentClass => ResourceManager.GetString(nameof(FloatingInterceptor_App_IntelligentClass), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoBoard5C => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoBoard5C), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoDesktopAnnotation => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoDesktopAnnotation), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoDesktopSideBar => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoDesktopSideBar), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoPinco => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoPinco), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoPincoDrawing => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoPincoDrawing), _resourceCulture);

        public static string FloatingInterceptor_App_SeewoPPTTools => ResourceManager.GetString(nameof(FloatingInterceptor_App_SeewoPPTTools), _resourceCulture);

        public static string FloatingInterceptor_Enable => ResourceManager.GetString(nameof(FloatingInterceptor_Enable), _resourceCulture);

        public static string FloatingInterceptor_Title => ResourceManager.GetString(nameof(FloatingInterceptor_Title), _resourceCulture);

        public static string FoldMode_AutoFoldAfterPPT => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterPPT), _resourceCulture);

        public static string FoldMode_AutoFoldAfterPPTHint => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterPPTHint), _resourceCulture);

        public static string FoldMode_AutoFoldAfterWhiteboard => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterWhiteboard), _resourceCulture);

        public static string FoldMode_AutoFoldAfterWhiteboardHint => ResourceManager.GetString(nameof(FoldMode_AutoFoldAfterWhiteboardHint), _resourceCulture);

        public static string FoldMode_ExitToAnnotation => ResourceManager.GetString(nameof(FoldMode_ExitToAnnotation), _resourceCulture);

        public static string FoldMode_ExitToAnnotationHint => ResourceManager.GetString(nameof(FoldMode_ExitToAnnotationHint), _resourceCulture);

        public static string AutoFold_Group_Seewo => ResourceManager.GetString(nameof(AutoFold_Group_Seewo), _resourceCulture);

        public static string AutoFold_Group_Hite => ResourceManager.GetString(nameof(AutoFold_Group_Hite), _resourceCulture);

        public static string AutoFold_Group_Other => ResourceManager.GetString(nameof(AutoFold_Group_Other), _resourceCulture);

        public static string FloatingInterceptor_Group_Seewo => ResourceManager.GetString(nameof(FloatingInterceptor_Group_Seewo), _resourceCulture);

        public static string FileAssoc_CheckDesc => ResourceManager.GetString(nameof(FileAssoc_CheckDesc), _resourceCulture);

        public static string FileAssoc_RegisterHeader => ResourceManager.GetString(nameof(FileAssoc_RegisterHeader), _resourceCulture);

        public static string FileAssoc_RegisterDesc => ResourceManager.GetString(nameof(FileAssoc_RegisterDesc), _resourceCulture);

        public static string FileAssoc_UnregisterDesc => ResourceManager.GetString(nameof(FileAssoc_UnregisterDesc), _resourceCulture);

        public static string FileAssoc_NotChecked => ResourceManager.GetString(nameof(FileAssoc_NotChecked), _resourceCulture);

        public static string FileAssoc_RegisterSuccess => ResourceManager.GetString(nameof(FileAssoc_RegisterSuccess), _resourceCulture);

        public static string FileAssoc_RegisterFailed => ResourceManager.GetString(nameof(FileAssoc_RegisterFailed), _resourceCulture);

        public static string FileAssoc_UnregisterSuccess => ResourceManager.GetString(nameof(FileAssoc_UnregisterSuccess), _resourceCulture);

        public static string FileAssoc_UnregisterFailed => ResourceManager.GetString(nameof(FileAssoc_UnregisterFailed), _resourceCulture);

        public static string FileAssoc_Registered => ResourceManager.GetString(nameof(FileAssoc_Registered), _resourceCulture);

        public static string FileAssoc_NotRegistered => ResourceManager.GetString(nameof(FileAssoc_NotRegistered), _resourceCulture);

        public static string FileAssoc_CheckError => ResourceManager.GetString(nameof(FileAssoc_CheckError), _resourceCulture);

        public static string Storage_AutoDeleteDaysThreshold => ResourceManager.GetString(nameof(Storage_AutoDeleteDaysThreshold), _resourceCulture);

        public static string Storage_MinAutomationStrokes => ResourceManager.GetString(nameof(Storage_MinAutomationStrokes), _resourceCulture);

        public static string FileAssoc_LoadedStrokesFile => ResourceManager.GetString(nameof(FileAssoc_LoadedStrokesFile), _resourceCulture);

        public static string FileAssoc_SwitchedToBoardMode => ResourceManager.GetString(nameof(FileAssoc_SwitchedToBoardMode), _resourceCulture);

        public static string FileAssoc_ExitedFoldMode => ResourceManager.GetString(nameof(FileAssoc_ExitedFoldMode), _resourceCulture);

        public static string AutoWf_StateSatisfied => ResourceManager.GetString(nameof(AutoWf_StateSatisfied), _resourceCulture);
        public static string AutoWf_StateNotSatisfied => ResourceManager.GetString(nameof(AutoWf_StateNotSatisfied), _resourceCulture);
        public static string AutoWf_StateUnknown => ResourceManager.GetString(nameof(AutoWf_StateUnknown), _resourceCulture);
        public static string AutoWf_AddWorkflow => ResourceManager.GetString(nameof(AutoWf_AddWorkflow), _resourceCulture);
        public static string AutoWf_Copy => ResourceManager.GetString(nameof(AutoWf_Copy), _resourceCulture);
        public static string AutoWf_Delete => ResourceManager.GetString(nameof(AutoWf_Delete), _resourceCulture);
        public static string AutoWf_Name => ResourceManager.GetString(nameof(AutoWf_Name), _resourceCulture);
        public static string AutoWf_EnableRevert => ResourceManager.GetString(nameof(AutoWf_EnableRevert), _resourceCulture);
        public static string AutoWf_Invoke => ResourceManager.GetString(nameof(AutoWf_Invoke), _resourceCulture);
        public static string AutoWf_Revert => ResourceManager.GetString(nameof(AutoWf_Revert), _resourceCulture);
        public static string AutoWf_WhenEvents => ResourceManager.GetString(nameof(AutoWf_WhenEvents), _resourceCulture);
        public static string AutoWf_AddTrigger => ResourceManager.GetString(nameof(AutoWf_AddTrigger), _resourceCulture);
        public static string AutoWf_AndConditions => ResourceManager.GetString(nameof(AutoWf_AndConditions), _resourceCulture);
        public static string AutoWf_ConditionDisabledHint => ResourceManager.GetString(nameof(AutoWf_ConditionDisabledHint), _resourceCulture);
        public static string AutoWf_AnyGroup => ResourceManager.GetString(nameof(AutoWf_AnyGroup), _resourceCulture);
        public static string AutoWf_AllGroups => ResourceManager.GetString(nameof(AutoWf_AllGroups), _resourceCulture);
        public static string AutoWf_Reverse => ResourceManager.GetString(nameof(AutoWf_Reverse), _resourceCulture);
        public static string AutoWf_AddGroup => ResourceManager.GetString(nameof(AutoWf_AddGroup), _resourceCulture);
        public static string AutoWf_AnyRule => ResourceManager.GetString(nameof(AutoWf_AnyRule), _resourceCulture);
        public static string AutoWf_AllRules => ResourceManager.GetString(nameof(AutoWf_AllRules), _resourceCulture);
        public static string AutoWf_AddRule => ResourceManager.GetString(nameof(AutoWf_AddRule), _resourceCulture);
        public static string AutoWf_EnableGroup => ResourceManager.GetString(nameof(AutoWf_EnableGroup), _resourceCulture);
        public static string AutoWf_Actions => ResourceManager.GetString(nameof(AutoWf_Actions), _resourceCulture);
        public static string AutoWf_AddAction => ResourceManager.GetString(nameof(AutoWf_AddAction), _resourceCulture);
        public static string AutoWf_AutoRevertHint => ResourceManager.GetString(nameof(AutoWf_AutoRevertHint), _resourceCulture);
        public static string AutoWf_EmptyState => ResourceManager.GetString(nameof(AutoWf_EmptyState), _resourceCulture);

        public static string Automation_Action_FoldToolbar => ResourceManager.GetString(nameof(Automation_Action_FoldToolbar), _resourceCulture);

        public static string Automation_Action_KillProcess => ResourceManager.GetString(nameof(Automation_Action_KillProcess), _resourceCulture);

        public static string Automation_Action_SaveStrokes => ResourceManager.GetString(nameof(Automation_Action_SaveStrokes), _resourceCulture);

        public static string Automation_Action_ToggleAnnotation => ResourceManager.GetString(nameof(Automation_Action_ToggleAnnotation), _resourceCulture);

        public static string Automation_Action_ClearStrokes => ResourceManager.GetString(nameof(Automation_Action_ClearStrokes), _resourceCulture);

        public static string Automation_Action_ShowNotification => ResourceManager.GetString(nameof(Automation_Action_ShowNotification), _resourceCulture);

        public static string Automation_Action_ToggleTopmost => ResourceManager.GetString(nameof(Automation_Action_ToggleTopmost), _resourceCulture);

        public static string Automation_Action_ResetDesktopPosition => ResourceManager.GetString(nameof(Automation_Action_ResetDesktopPosition), _resourceCulture);

        public static string Automation_Action_ResetPptPosition => ResourceManager.GetString(nameof(Automation_Action_ResetPptPosition), _resourceCulture);

        public static string Automation_Rule_ProcessRunning => ResourceManager.GetString(nameof(Automation_Rule_ProcessRunning), _resourceCulture);

        public static string Automation_Rule_WindowTitleContains => ResourceManager.GetString(nameof(Automation_Rule_WindowTitleContains), _resourceCulture);

        public static string Automation_Rule_IsAnnotationMode => ResourceManager.GetString(nameof(Automation_Rule_IsAnnotationMode), _resourceCulture);

        public static string Automation_Rule_IsPptSlideshow => ResourceManager.GetString(nameof(Automation_Rule_IsPptSlideshow), _resourceCulture);

        public static string Automation_Rule_ForegroundWindowProcess => ResourceManager.GetString(nameof(Automation_Rule_ForegroundWindowProcess), _resourceCulture);

        public static string Automation_Rule_IsFloatingBarFolded => ResourceManager.GetString(nameof(Automation_Rule_IsFloatingBarFolded), _resourceCulture);

        public static string Automation_Rule_IsForegroundWhiteboard => ResourceManager.GetString(nameof(Automation_Rule_IsForegroundWhiteboard), _resourceCulture);

        public static string Automation_SlideShow => ResourceManager.GetString(nameof(Automation_SlideShow), _resourceCulture);

        public static string Automation_Trigger_WhiteboardEnter => ResourceManager.GetString(nameof(Automation_Trigger_WhiteboardEnter), _resourceCulture);

        public static string Automation_Trigger_WhiteboardExit => ResourceManager.GetString(nameof(Automation_Trigger_WhiteboardExit), _resourceCulture);

        public static string Automation_Trigger_AnnotationEnter => ResourceManager.GetString(nameof(Automation_Trigger_AnnotationEnter), _resourceCulture);

        public static string Automation_Trigger_AnnotationExit => ResourceManager.GetString(nameof(Automation_Trigger_AnnotationExit), _resourceCulture);

        public static string Automation_Trigger_PptEnter => ResourceManager.GetString(nameof(Automation_Trigger_PptEnter), _resourceCulture);

        public static string Automation_Trigger_PptExit => ResourceManager.GetString(nameof(Automation_Trigger_PptExit), _resourceCulture);

        public static string Automation_Trigger_PptDetection => ResourceManager.GetString(nameof(Automation_Trigger_PptDetection), _resourceCulture);

        public static string Automation_Trigger_ProcessDetected => ResourceManager.GetString(nameof(Automation_Trigger_ProcessDetected), _resourceCulture);

        public static string Automation_Trigger_RulesetChanged => ResourceManager.GetString(nameof(Automation_Trigger_RulesetChanged), _resourceCulture);

        public static string Automation_Trigger_Timer => ResourceManager.GetString(nameof(Automation_Trigger_Timer), _resourceCulture);

        public static string Automation_Trigger_WindowFocusChanged => ResourceManager.GetString(nameof(Automation_Trigger_WindowFocusChanged), _resourceCulture);

        public static string Automation_DefaultActionName => ResourceManager.GetString(nameof(Automation_DefaultActionName), _resourceCulture);

        public static string Automation_Workflow_CopySuffix => ResourceManager.GetString(nameof(Automation_Workflow_CopySuffix), _resourceCulture);

        public static string Automation_Field_ProcessName => ResourceManager.GetString(nameof(Automation_Field_ProcessName), _resourceCulture);

        public static string Automation_Field_TitleContains => ResourceManager.GetString(nameof(Automation_Field_TitleContains), _resourceCulture);

        public static string Automation_Field_IgnoreCase => ResourceManager.GetString(nameof(Automation_Field_IgnoreCase), _resourceCulture);

        public static string Automation_Field_NotificationType => ResourceManager.GetString(nameof(Automation_Field_NotificationType), _resourceCulture);

        public static string Automation_Field_NotificationContent => ResourceManager.GetString(nameof(Automation_Field_NotificationContent), _resourceCulture);

        public static string Automation_Field_SavePath => ResourceManager.GetString(nameof(Automation_Field_SavePath), _resourceCulture);

        public static string Automation_Field_SaveAsXml => ResourceManager.GetString(nameof(Automation_Field_SaveAsXml), _resourceCulture);

        public static string Automation_Field_Fold => ResourceManager.GetString(nameof(Automation_Field_Fold), _resourceCulture);

        public static string Automation_Field_EnterAnnotation => ResourceManager.GetString(nameof(Automation_Field_EnterAnnotation), _resourceCulture);

        public static string Automation_Field_Topmost => ResourceManager.GetString(nameof(Automation_Field_Topmost), _resourceCulture);

        public static string Automation_Workflow_DefaultNameFormat => ResourceManager.GetString(nameof(Automation_Workflow_DefaultNameFormat), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoBoard3 => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoBoard3), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoBoard5 => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoBoard5), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoBoard5C => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoBoard5C), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoPincoDesktop => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoPincoDesktop), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoPincoPen => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoPincoPen), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoPincoBoard => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoPincoBoard), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoPptTools => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoPptTools), _resourceCulture);

        public static string FloatingInterceptor_Rule_AiClass => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_AiClass), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanMain => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanMain), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanPenSettings => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanPenSettings), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanSwipeClear => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanSwipeClear), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanInteraction => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanInteraction), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanSubject => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanSubject), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanControl => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanControl), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanTools => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanTools), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanSceneBar => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanSceneBar), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanDrawWindow => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanDrawWindow), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanPptFloat => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanPptFloat), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanPptPage => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanPptPage), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanPptBack => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanPptBack), _resourceCulture);

        public static string FloatingInterceptor_Rule_ChangYanPptPreview => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_ChangYanPptPreview), _resourceCulture);

        public static string FloatingInterceptor_Rule_IntelligentClassDesktop => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_IntelligentClassDesktop), _resourceCulture);

        public static string FloatingInterceptor_Rule_IntelligentClassPptFloat => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_IntelligentClassPptFloat), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoDesktopPen => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoDesktopPen), _resourceCulture);

        public static string FloatingInterceptor_Rule_SeewoDesktopSideBar => ResourceManager.GetString(nameof(FloatingInterceptor_Rule_SeewoDesktopSideBar), _resourceCulture);
    }
}