//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from BoothStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class BoothStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.BoothStrings", typeof(BoothStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string CameraDevices => ResourceManager.GetString(nameof(CameraDevices), _resourceCulture);

        public static string Capture => ResourceManager.GetString(nameof(Capture), _resourceCulture);

        public static string CapturedPhotos => ResourceManager.GetString(nameof(CapturedPhotos), _resourceCulture);

        public static string Close => ResourceManager.GetString(nameof(Close), _resourceCulture);

        public static string Correction => ResourceManager.GetString(nameof(Correction), _resourceCulture);

        public static string Present => ResourceManager.GetString(nameof(Present), _resourceCulture);

        public static string Resolution_Tooltip => ResourceManager.GetString(nameof(Resolution_Tooltip), _resourceCulture);

        public static string Rotate => ResourceManager.GetString(nameof(Rotate), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);
    }
}