//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from CloudStorageStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class CloudStorageStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.CloudStorageStrings", typeof(CloudStorageStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string CloudStorage_Manage => ResourceManager.GetString(nameof(CloudStorage_Manage), _resourceCulture);

        public static string CloudStorage_UploadDelay => ResourceManager.GetString(nameof(CloudStorage_UploadDelay), _resourceCulture);

        public static string CloudStorage_UploadDelayDesc => ResourceManager.GetString(nameof(CloudStorage_UploadDelayDesc), _resourceCulture);

        public static string CloudStorage_Minutes => ResourceManager.GetString(nameof(CloudStorage_Minutes), _resourceCulture);

        public static string CloudStorage_UploadProviders => ResourceManager.GetString(nameof(CloudStorage_UploadProviders), _resourceCulture);

        public static string CloudStorage_UploadProvidersDesc => ResourceManager.GetString(nameof(CloudStorage_UploadProvidersDesc), _resourceCulture);

        public static string CloudStorage_ProviderList => ResourceManager.GetString(nameof(CloudStorage_ProviderList), _resourceCulture);

        public static string CloudStorage_ProviderListDesc => ResourceManager.GetString(nameof(CloudStorage_ProviderListDesc), _resourceCulture);

        public static string CloudStorage_Dlass => ResourceManager.GetString(nameof(CloudStorage_Dlass), _resourceCulture);

        public static string CloudStorage_UserToken => ResourceManager.GetString(nameof(CloudStorage_UserToken), _resourceCulture);

        public static string CloudStorage_UserTokenDesc => ResourceManager.GetString(nameof(CloudStorage_UserTokenDesc), _resourceCulture);

        public static string CloudStorage_TokenNotSet => ResourceManager.GetString(nameof(CloudStorage_TokenNotSet), _resourceCulture);

        public static string CloudStorage_SavedTokens => ResourceManager.GetString(nameof(CloudStorage_SavedTokens), _resourceCulture);

        public static string CloudStorage_SavedTokensDesc => ResourceManager.GetString(nameof(CloudStorage_SavedTokensDesc), _resourceCulture);

        public static string CloudStorage_NewToken => ResourceManager.GetString(nameof(CloudStorage_NewToken), _resourceCulture);

        public static string CloudStorage_NewTokenDesc => ResourceManager.GetString(nameof(CloudStorage_NewTokenDesc), _resourceCulture);

        public static string CloudStorage_TokenActions => ResourceManager.GetString(nameof(CloudStorage_TokenActions), _resourceCulture);

        public static string CloudStorage_SaveToken => ResourceManager.GetString(nameof(CloudStorage_SaveToken), _resourceCulture);

        public static string CloudStorage_DeleteToken => ResourceManager.GetString(nameof(CloudStorage_DeleteToken), _resourceCulture);

        public static string CloudStorage_OpenDlassDashboard => ResourceManager.GetString(nameof(CloudStorage_OpenDlassDashboard), _resourceCulture);

        public static string CloudStorage_ConnectionStatus => ResourceManager.GetString(nameof(CloudStorage_ConnectionStatus), _resourceCulture);

        public static string CloudStorage_ConnectionStatusDesc => ResourceManager.GetString(nameof(CloudStorage_ConnectionStatusDesc), _resourceCulture);

        public static string CloudStorage_NotConnected => ResourceManager.GetString(nameof(CloudStorage_NotConnected), _resourceCulture);

        public static string CloudStorage_TestConnection => ResourceManager.GetString(nameof(CloudStorage_TestConnection), _resourceCulture);

        public static string CloudStorage_ClassSelection => ResourceManager.GetString(nameof(CloudStorage_ClassSelection), _resourceCulture);

        public static string CloudStorage_ClassSelectionDesc => ResourceManager.GetString(nameof(CloudStorage_ClassSelectionDesc), _resourceCulture);

        public static string CloudStorage_AutoUploadNotes => ResourceManager.GetString(nameof(CloudStorage_AutoUploadNotes), _resourceCulture);

        public static string CloudStorage_AutoUploadNotesDesc => ResourceManager.GetString(nameof(CloudStorage_AutoUploadNotesDesc), _resourceCulture);

        public static string CloudStorage_WebDav => ResourceManager.GetString(nameof(CloudStorage_WebDav), _resourceCulture);

        public static string CloudStorage_WebDavSettings => ResourceManager.GetString(nameof(CloudStorage_WebDavSettings), _resourceCulture);

        public static string CloudStorage_WebDavSettingsDesc => ResourceManager.GetString(nameof(CloudStorage_WebDavSettingsDesc), _resourceCulture);

        public static string CloudStorage_WebDavUrl => ResourceManager.GetString(nameof(CloudStorage_WebDavUrl), _resourceCulture);

        public static string CloudStorage_WebDavUrlDesc => ResourceManager.GetString(nameof(CloudStorage_WebDavUrlDesc), _resourceCulture);

        public static string CloudStorage_Username => ResourceManager.GetString(nameof(CloudStorage_Username), _resourceCulture);

        public static string CloudStorage_Password => ResourceManager.GetString(nameof(CloudStorage_Password), _resourceCulture);

        public static string CloudStorage_RootDirectory => ResourceManager.GetString(nameof(CloudStorage_RootDirectory), _resourceCulture);

        public static string CloudStorage_RootDirectoryDesc => ResourceManager.GetString(nameof(CloudStorage_RootDirectoryDesc), _resourceCulture);

        public static string CloudStorage_WebDavActions => ResourceManager.GetString(nameof(CloudStorage_WebDavActions), _resourceCulture);

        public static string CloudStorage_SaveWebDavSettings => ResourceManager.GetString(nameof(CloudStorage_SaveWebDavSettings), _resourceCulture);

        public static string CloudStorage_Restore => ResourceManager.GetString(nameof(CloudStorage_Restore), _resourceCulture);

        public static string CloudStorage_NoSavedToken => ResourceManager.GetString(nameof(CloudStorage_NoSavedToken), _resourceCulture);

        public static string CloudStorage_WaitingForConnection => ResourceManager.GetString(nameof(CloudStorage_WaitingForConnection), _resourceCulture);

        public static string CloudStorage_UnknownTeacher => ResourceManager.GetString(nameof(CloudStorage_UnknownTeacher), _resourceCulture);

        public static string CloudStorage_NoAvailableClasses => ResourceManager.GetString(nameof(CloudStorage_NoAvailableClasses), _resourceCulture);

        public static string CloudStorage_PleaseEnterNewToken => ResourceManager.GetString(nameof(CloudStorage_PleaseEnterNewToken), _resourceCulture);

        public static string CloudStorage_Tip => ResourceManager.GetString(nameof(CloudStorage_Tip), _resourceCulture);

        public static string CloudStorage_TokenSavedAndSelected => ResourceManager.GetString(nameof(CloudStorage_TokenSavedAndSelected), _resourceCulture);

        public static string CloudStorage_Success => ResourceManager.GetString(nameof(CloudStorage_Success), _resourceCulture);

        public static string CloudStorage_SaveTokenError => ResourceManager.GetString(nameof(CloudStorage_SaveTokenError), _resourceCulture);

        public static string CloudStorage_Error => ResourceManager.GetString(nameof(CloudStorage_Error), _resourceCulture);

        public static string CloudStorage_PleaseSelectToken => ResourceManager.GetString(nameof(CloudStorage_PleaseSelectToken), _resourceCulture);

        public static string CloudStorage_ConfirmDeleteToken => ResourceManager.GetString(nameof(CloudStorage_ConfirmDeleteToken), _resourceCulture);

        public static string CloudStorage_Confirm => ResourceManager.GetString(nameof(CloudStorage_Confirm), _resourceCulture);

        public static string CloudStorage_WebDavSettingsSaved => ResourceManager.GetString(nameof(CloudStorage_WebDavSettingsSaved), _resourceCulture);

        public static string CloudStorage_SaveWebDavError => ResourceManager.GetString(nameof(CloudStorage_SaveWebDavError), _resourceCulture);

        public static string CloudStorage_DlassRegistrationPrompt => ResourceManager.GetString(nameof(CloudStorage_DlassRegistrationPrompt), _resourceCulture);

        public static string CloudStorage_DlassRegistrationTitle => ResourceManager.GetString(nameof(CloudStorage_DlassRegistrationTitle), _resourceCulture);

        public static string CloudStorage_CannotOpenBrowser => ResourceManager.GetString(nameof(CloudStorage_CannotOpenBrowser), _resourceCulture);

        public static string CloudStorage_Testing => ResourceManager.GetString(nameof(CloudStorage_Testing), _resourceCulture);

        public static string CloudStorage_ConnectedFormat => ResourceManager.GetString(nameof(CloudStorage_ConnectedFormat), _resourceCulture);

        public static string CloudStorage_ConnectionFailed => ResourceManager.GetString(nameof(CloudStorage_ConnectionFailed), _resourceCulture);

        public static string CloudStorage_DeleteTokenError => ResourceManager.GetString(nameof(CloudStorage_DeleteTokenError), _resourceCulture);

        public static string CloudStorage_TokenSelected => ResourceManager.GetString(nameof(CloudStorage_TokenSelected), _resourceCulture);
    }
}