//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from CommonStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class CommonStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.CommonStrings", typeof(CommonStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Color => ResourceManager.GetString(nameof(Color), _resourceCulture);

        public static string Common_Cancel => ResourceManager.GetString(nameof(Common_Cancel), _resourceCulture);

        public static string Hotkey_NotSet => ResourceManager.GetString(nameof(Hotkey_NotSet), _resourceCulture);

        public static string Mode_PPTOnly => ResourceManager.GetString(nameof(Mode_PPTOnly), _resourceCulture);

        public static string No => ResourceManager.GetString(nameof(No), _resourceCulture);

        public static string Size_Medium => ResourceManager.GetString(nameof(Size_Medium), _resourceCulture);

        public static string Size_Small => ResourceManager.GetString(nameof(Size_Small), _resourceCulture);

        public static string Time_End => ResourceManager.GetString(nameof(Time_End), _resourceCulture);

        public static string Time_Start => ResourceManager.GetString(nameof(Time_Start), _resourceCulture);

        public static string Yes => ResourceManager.GetString(nameof(Yes), _resourceCulture);

        public static string Common_OK => ResourceManager.GetString(nameof(Common_OK), _resourceCulture);

        public static string Common_On => ResourceManager.GetString(nameof(Common_On), _resourceCulture);

        public static string Common_Off => ResourceManager.GetString(nameof(Common_Off), _resourceCulture);

        public static string SettingsTag_Warn => ResourceManager.GetString(nameof(SettingsTag_Warn), _resourceCulture);

        public static string SettingsTag_New => ResourceManager.GetString(nameof(SettingsTag_New), _resourceCulture);

        public static string SettingsTag_Experimental => ResourceManager.GetString(nameof(SettingsTag_Experimental), _resourceCulture);

        public static string SettingsTag_Secret => ResourceManager.GetString(nameof(SettingsTag_Secret), _resourceCulture);

        public static string SettingsTag_Favourite => ResourceManager.GetString(nameof(SettingsTag_Favourite), _resourceCulture);

        public static string SettingsItemMore => ResourceManager.GetString(nameof(SettingsItemMore), _resourceCulture);

        public static string SettingsItemCopyKey => ResourceManager.GetString(nameof(SettingsItemCopyKey), _resourceCulture);

        public static string SettingsItemCopyUrl => ResourceManager.GetString(nameof(SettingsItemCopyUrl), _resourceCulture);

        public static string SettingsItemAddFavourite => ResourceManager.GetString(nameof(SettingsItemAddFavourite), _resourceCulture);

        public static string SettingsItemRemoveFavourite => ResourceManager.GetString(nameof(SettingsItemRemoveFavourite), _resourceCulture);
    }
}