//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from ConfigStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class ConfigStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.ConfigStrings", typeof(ConfigStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Delete => ResourceManager.GetString(nameof(Delete), _resourceCulture);

        public static string Desc => ResourceManager.GetString(nameof(Desc), _resourceCulture);

        public static string Label => ResourceManager.GetString(nameof(Label), _resourceCulture);

        public static string SaveAs => ResourceManager.GetString(nameof(SaveAs), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);

        public static string ProfileNameLabel => ResourceManager.GetString(nameof(ProfileNameLabel), _resourceCulture);

        public static string SaveAsProfileTitle => ResourceManager.GetString(nameof(SaveAsProfileTitle), _resourceCulture);

        public static string SaveAs_EnterName => ResourceManager.GetString(nameof(SaveAs_EnterName), _resourceCulture);

        public static string SavedAsProfile => ResourceManager.GetString(nameof(SavedAsProfile), _resourceCulture);

        public static string SaveAs_Failed => ResourceManager.GetString(nameof(SaveAs_Failed), _resourceCulture);

        public static string SaveAs_FailedMsg => ResourceManager.GetString(nameof(SaveAs_FailedMsg), _resourceCulture);

        public static string Delete_SelectFirst => ResourceManager.GetString(nameof(Delete_SelectFirst), _resourceCulture);

        public static string Delete_ConfirmTitle => ResourceManager.GetString(nameof(Delete_ConfirmTitle), _resourceCulture);

        public static string Delete_ConfirmMsg => ResourceManager.GetString(nameof(Delete_ConfirmMsg), _resourceCulture);

        public static string Delete_Failed => ResourceManager.GetString(nameof(Delete_Failed), _resourceCulture);

        public static string Delete_FailedMsg => ResourceManager.GetString(nameof(Delete_FailedMsg), _resourceCulture);

        public static string SwitchedToProfile => ResourceManager.GetString(nameof(SwitchedToProfile), _resourceCulture);

        public static string DeletedAndSwitched => ResourceManager.GetString(nameof(DeletedAndSwitched), _resourceCulture);

        public static string DeletedProfile => ResourceManager.GetString(nameof(DeletedProfile), _resourceCulture);
    }
}