//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from FloatingBarStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class FloatingBarStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.FloatingBarStrings", typeof(FloatingBarStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Board_Background => ResourceManager.GetString(nameof(Board_Background), _resourceCulture);

        public static string Board_ClearInk => ResourceManager.GetString(nameof(Board_ClearInk), _resourceCulture);

        public static string Board_ClearInkAndHistory => ResourceManager.GetString(nameof(Board_ClearInkAndHistory), _resourceCulture);

        public static string Board_DeleteThisPage => ResourceManager.GetString(nameof(Board_DeleteThisPage), _resourceCulture);

        public static string Board_Eraser => ResourceManager.GetString(nameof(Board_Eraser), _resourceCulture);

        public static string Board_EraserOptions => ResourceManager.GetString(nameof(Board_EraserOptions), _resourceCulture);

        public static string Board_EraserShape_Blackboard => ResourceManager.GetString(nameof(Board_EraserShape_Blackboard), _resourceCulture);

        public static string Board_EraserShape_Circle => ResourceManager.GetString(nameof(Board_EraserShape_Circle), _resourceCulture);

        public static string Board_Gesture => ResourceManager.GetString(nameof(Board_Gesture), _resourceCulture);

        public static string Board_Highlighter => ResourceManager.GetString(nameof(Board_Highlighter), _resourceCulture);

        public static string Board_InsertImage => ResourceManager.GetString(nameof(Board_InsertImage), _resourceCulture);

        public static string Board_LaserPen => ResourceManager.GetString(nameof(Board_LaserPen), _resourceCulture);

        public static string Board_NewPage => ResourceManager.GetString(nameof(Board_NewPage), _resourceCulture);

        public static string Board_NextPage => ResourceManager.GetString(nameof(Board_NextPage), _resourceCulture);

        public static string Board_Page => ResourceManager.GetString(nameof(Board_Page), _resourceCulture);

        public static string Board_Pen => ResourceManager.GetString(nameof(Board_Pen), _resourceCulture);

        public static string Board_PreviousPage => ResourceManager.GetString(nameof(Board_PreviousPage), _resourceCulture);

        public static string Board_Redo => ResourceManager.GetString(nameof(Board_Redo), _resourceCulture);

        public static string Board_Screenshot => ResourceManager.GetString(nameof(Board_Screenshot), _resourceCulture);

        public static string Board_Select => ResourceManager.GetString(nameof(Board_Select), _resourceCulture);

        public static string Board_SelectImage => ResourceManager.GetString(nameof(Board_SelectImage), _resourceCulture);

        public static string Board_Shape => ResourceManager.GetString(nameof(Board_Shape), _resourceCulture);

        public static string Board_Size => ResourceManager.GetString(nameof(Board_Size), _resourceCulture);
        
        public static string Board_StrokeEraser => ResourceManager.GetString(nameof(Board_StrokeEraser), _resourceCulture);

        public static string Board_Tools => ResourceManager.GetString(nameof(Board_Tools), _resourceCulture);

        public static string Board_TwoFingerMove => ResourceManager.GetString(nameof(Board_TwoFingerMove), _resourceCulture);

        public static string Board_Undo => ResourceManager.GetString(nameof(Board_Undo), _resourceCulture);

        public static string FloatingBar_Annotate => ResourceManager.GetString(nameof(FloatingBar_Annotate), _resourceCulture);

        public static string FloatingBar_AreaEraser => ResourceManager.GetString(nameof(FloatingBar_AreaEraser), _resourceCulture);

        public static string FloatingBar_Clear => ResourceManager.GetString(nameof(FloatingBar_Clear), _resourceCulture);

        public static string FloatingBar_ClearAndMouse => ResourceManager.GetString(nameof(FloatingBar_ClearAndMouse), _resourceCulture);

        public static string FloatingBar_ExitButton => ResourceManager.GetString(nameof(FloatingBar_ExitButton), _resourceCulture);

        public static string FloatingBar_Freeze => ResourceManager.GetString(nameof(FloatingBar_Freeze), _resourceCulture);

        public static string FloatingBar_Geometry => ResourceManager.GetString(nameof(FloatingBar_Geometry), _resourceCulture);

        public static string FloatingBar_Gesture_MultiTouchWriting => ResourceManager.GetString(nameof(FloatingBar_Gesture_MultiTouchWriting), _resourceCulture);

        public static string FloatingBar_Gesture_TwoFingerRotate => ResourceManager.GetString(nameof(FloatingBar_Gesture_TwoFingerRotate), _resourceCulture);

        public static string FloatingBar_Gesture_TwoFingerZoom => ResourceManager.GetString(nameof(FloatingBar_Gesture_TwoFingerZoom), _resourceCulture);

        public static string FloatingBar_GestureButton => ResourceManager.GetString(nameof(FloatingBar_GestureButton), _resourceCulture);

        public static string FloatingBar_Hide => ResourceManager.GetString(nameof(FloatingBar_Hide), _resourceCulture);

        public static string FloatingBar_LassoSelect => ResourceManager.GetString(nameof(FloatingBar_LassoSelect), _resourceCulture);

        public static string FloatingBar_Mouse => ResourceManager.GetString(nameof(FloatingBar_Mouse), _resourceCulture);

        public static string FloatingBar_StrokeEraser => ResourceManager.GetString(nameof(FloatingBar_StrokeEraser), _resourceCulture);

        public static string FloatingBar_Unfreeze => ResourceManager.GetString(nameof(FloatingBar_Unfreeze), _resourceCulture);

        public static string FloatingBar_Whiteboard => ResourceManager.GetString(nameof(FloatingBar_Whiteboard), _resourceCulture);

        public static string OldUI_Dark => ResourceManager.GetString(nameof(OldUI_Dark), _resourceCulture);

        public static string OldUI_Exit => ResourceManager.GetString(nameof(OldUI_Exit), _resourceCulture);

        public static string OldUI_Thickness => ResourceManager.GetString(nameof(OldUI_Thickness), _resourceCulture);

        public static string QuickPanel_ExitShow => ResourceManager.GetString(nameof(QuickPanel_ExitShow), _resourceCulture);

        public static string QuickPanel_Show => ResourceManager.GetString(nameof(QuickPanel_Show), _resourceCulture);

        public static string QuickPanel_SingleDraw => ResourceManager.GetString(nameof(QuickPanel_SingleDraw), _resourceCulture);

        public static string QuickPanel_Timer => ResourceManager.GetString(nameof(QuickPanel_Timer), _resourceCulture);

        public static string Tools_Manual => ResourceManager.GetString(nameof(Tools_Manual), _resourceCulture);

        public static string Tools_MoreFeaturesTitle => ResourceManager.GetString(nameof(Tools_MoreFeaturesTitle), _resourceCulture);

        public static string Tools_Open => ResourceManager.GetString(nameof(Tools_Open), _resourceCulture);

        public static string Tools_RandomDraw => ResourceManager.GetString(nameof(Tools_RandomDraw), _resourceCulture);

        public static string Tools_Replay => ResourceManager.GetString(nameof(Tools_Replay), _resourceCulture);

        public static string Tools_Save => ResourceManager.GetString(nameof(Tools_Save), _resourceCulture);

        public static string Tools_Screenshot => ResourceManager.GetString(nameof(Tools_Screenshot), _resourceCulture);

        public static string ToolbarCondition_Annotating => ResourceManager.GetString(nameof(ToolbarCondition_Annotating), _resourceCulture);

        public static string ToolbarCondition_Collapsed => ResourceManager.GetString(nameof(ToolbarCondition_Collapsed), _resourceCulture);

        public static string ToolbarCondition_PPTMode => ResourceManager.GetString(nameof(ToolbarCondition_PPTMode), _resourceCulture);

        public static string ToolbarItem_Desc_Clear => ResourceManager.GetString(nameof(ToolbarItem_Desc_Clear), _resourceCulture);

        public static string ToolbarItem_Desc_Cursor => ResourceManager.GetString(nameof(ToolbarItem_Desc_Cursor), _resourceCulture);

        public static string ToolbarItem_Desc_CursorWithDel => ResourceManager.GetString(nameof(ToolbarItem_Desc_CursorWithDel), _resourceCulture);

        public static string ToolbarItem_Desc_Eraser => ResourceManager.GetString(nameof(ToolbarItem_Desc_Eraser), _resourceCulture);

        public static string ToolbarItem_Desc_Exit => ResourceManager.GetString(nameof(ToolbarItem_Desc_Exit), _resourceCulture);

        public static string ToolbarItem_Desc_Fold => ResourceManager.GetString(nameof(ToolbarItem_Desc_Fold), _resourceCulture);

        public static string ToolbarItem_Desc_Gesture => ResourceManager.GetString(nameof(ToolbarItem_Desc_Gesture), _resourceCulture);

        public static string ToolbarItem_Desc_Group => ResourceManager.GetString(nameof(ToolbarItem_Desc_Group), _resourceCulture);

        public static string ToolbarItem_Desc_InkFreeze => ResourceManager.GetString(nameof(ToolbarItem_Desc_InkFreeze), _resourceCulture);

        public static string ToolbarItem_Desc_Pen => ResourceManager.GetString(nameof(ToolbarItem_Desc_Pen), _resourceCulture);

        public static string ToolbarItem_Desc_QuickColorPalette => ResourceManager.GetString(nameof(ToolbarItem_Desc_QuickColorPalette), _resourceCulture);

        public static string ToolbarItem_Desc_Select => ResourceManager.GetString(nameof(ToolbarItem_Desc_Select), _resourceCulture);

        public static string ToolbarItem_Desc_Separator => ResourceManager.GetString(nameof(ToolbarItem_Desc_Separator), _resourceCulture);

        public static string ToolbarItem_Desc_StrokeEraser => ResourceManager.GetString(nameof(ToolbarItem_Desc_StrokeEraser), _resourceCulture);

        public static string ToolbarPage_AddGroup => ResourceManager.GetString(nameof(ToolbarPage_AddGroup), _resourceCulture);

        public static string ToolbarPage_Alignment => ResourceManager.GetString(nameof(ToolbarPage_Alignment), _resourceCulture);

        public static string ToolbarPage_AddedComponents => ResourceManager.GetString(nameof(ToolbarPage_AddedComponents), _resourceCulture);

        public static string ToolbarPage_AddedComponentsHint => ResourceManager.GetString(nameof(ToolbarPage_AddedComponentsHint), _resourceCulture);

        public static string ToolbarPage_AddToAdded => ResourceManager.GetString(nameof(ToolbarPage_AddToAdded), _resourceCulture);

        public static string ToolbarPage_AllConditionGroupsMet => ResourceManager.GetString(nameof(ToolbarPage_AllConditionGroupsMet), _resourceCulture);

        public static string ToolbarPage_AllConditionsMet => ResourceManager.GetString(nameof(ToolbarPage_AllConditionsMet), _resourceCulture);

        public static string ToolbarPage_AnyConditionGroupMet => ResourceManager.GetString(nameof(ToolbarPage_AnyConditionGroupMet), _resourceCulture);

        public static string ToolbarPage_AnyConditionMet => ResourceManager.GetString(nameof(ToolbarPage_AnyConditionMet), _resourceCulture);

        public static string ToolbarPage_Appearance => ResourceManager.GetString(nameof(ToolbarPage_Appearance), _resourceCulture);

        public static string ToolbarPage_AtLeastOneConfig => ResourceManager.GetString(nameof(ToolbarPage_AtLeastOneConfig), _resourceCulture);

        public static string ToolbarPage_Bottom => ResourceManager.GetString(nameof(ToolbarPage_Bottom), _resourceCulture);

        public static string ToolbarPage_Cancel => ResourceManager.GetString(nameof(ToolbarPage_Cancel), _resourceCulture);

        public static string ToolbarPage_Center => ResourceManager.GetString(nameof(ToolbarPage_Center), _resourceCulture);

        public static string ToolbarPage_ComponentLibrary => ResourceManager.GetString(nameof(ToolbarPage_ComponentLibrary), _resourceCulture);

        public static string ToolbarPage_ComponentLibraryHint => ResourceManager.GetString(nameof(ToolbarPage_ComponentLibraryHint), _resourceCulture);

        public static string ToolbarPage_ComponentProperties => ResourceManager.GetString(nameof(ToolbarPage_ComponentProperties), _resourceCulture);

        public static string ToolbarPage_ComponentSettings => ResourceManager.GetString(nameof(ToolbarPage_ComponentSettings), _resourceCulture);

        public static string ToolbarPage_ConfigProfiles => ResourceManager.GetString(nameof(ToolbarPage_ConfigProfiles), _resourceCulture);

        public static string ToolbarPage_ConfirmDelete => ResourceManager.GetString(nameof(ToolbarPage_ConfirmDelete), _resourceCulture);

        public static string ToolbarPage_ConfirmDeleteConfig => ResourceManager.GetString(nameof(ToolbarPage_ConfirmDeleteConfig), _resourceCulture);

        public static string ToolbarPage_CopyConfig => ResourceManager.GetString(nameof(ToolbarPage_CopyConfig), _resourceCulture);

        public static string ToolbarPage_DeleteProfile => ResourceManager.GetString(nameof(ToolbarPage_DeleteProfile), _resourceCulture);

        public static string ToolbarPage_DisplayMode => ResourceManager.GetString(nameof(ToolbarPage_DisplayMode), _resourceCulture);

        public static string ToolbarPage_Duplicate => ResourceManager.GetString(nameof(ToolbarPage_Duplicate), _resourceCulture);

        public static string ToolbarPage_DuplicateConfigExists => ResourceManager.GetString(nameof(ToolbarPage_DuplicateConfigExists), _resourceCulture);

        public static string ToolbarPage_OpenConfigFolder => ResourceManager.GetString(nameof(ToolbarPage_OpenConfigFolder), _resourceCulture);

        public static string ToolbarPage_RefreshProfile => ResourceManager.GetString(nameof(ToolbarPage_RefreshProfile), _resourceCulture);

        public static string ToolbarPage_DuplicateProfile => ResourceManager.GetString(nameof(ToolbarPage_DuplicateProfile), _resourceCulture);

        public static string ToolbarPage_EnableConditionGroup => ResourceManager.GetString(nameof(ToolbarPage_EnableConditionGroup), _resourceCulture);

        public static string ToolbarPage_EnterConfigName => ResourceManager.GetString(nameof(ToolbarPage_EnterConfigName), _resourceCulture);

        public static string ToolbarPage_EnterNewConfigName => ResourceManager.GetString(nameof(ToolbarPage_EnterNewConfigName), _resourceCulture);

        public static string ToolbarPage_FontSize => ResourceManager.GetString(nameof(ToolbarPage_FontSize), _resourceCulture);

        public static string ToolbarPage_FixedHeight => ResourceManager.GetString(nameof(ToolbarPage_FixedHeight), _resourceCulture);

        public static string ToolbarPage_FixedWidth => ResourceManager.GetString(nameof(ToolbarPage_FixedWidth), _resourceCulture);

        public static string ToolbarPage_GroupChildren => ResourceManager.GetString(nameof(ToolbarPage_GroupChildren), _resourceCulture);

        public static string ToolbarPage_GroupChildrenHint => ResourceManager.GetString(nameof(ToolbarPage_GroupChildrenHint), _resourceCulture);

        public static string ToolbarPage_HideByRules => ResourceManager.GetString(nameof(ToolbarPage_HideByRules), _resourceCulture);

        public static string ToolbarPage_HideByRulesDesc => ResourceManager.GetString(nameof(ToolbarPage_HideByRulesDesc), _resourceCulture);

        public static string ToolbarPage_Hint => ResourceManager.GetString(nameof(ToolbarPage_Hint), _resourceCulture);

        public static string ToolbarPage_HorizontalAlignment => ResourceManager.GetString(nameof(ToolbarPage_HorizontalAlignment), _resourceCulture);

        public static string ToolbarPage_IconSize => ResourceManager.GetString(nameof(ToolbarPage_IconSize), _resourceCulture);

        public static string ToolbarPage_Left => ResourceManager.GetString(nameof(ToolbarPage_Left), _resourceCulture);

        public static string ToolbarPage_Margin => ResourceManager.GetString(nameof(ToolbarPage_Margin), _resourceCulture);

        public static string ToolbarPage_MarginHint => ResourceManager.GetString(nameof(ToolbarPage_MarginHint), _resourceCulture);

        public static string ToolbarPage_MaxHeight => ResourceManager.GetString(nameof(ToolbarPage_MaxHeight), _resourceCulture);

        public static string ToolbarPage_MaxWidth => ResourceManager.GetString(nameof(ToolbarPage_MaxWidth), _resourceCulture);

        public static string ToolbarPage_MinHeight => ResourceManager.GetString(nameof(ToolbarPage_MinHeight), _resourceCulture);

        public static string ToolbarPage_MinWidth => ResourceManager.GetString(nameof(ToolbarPage_MinWidth), _resourceCulture);

        public static string ToolbarPage_NewConfig => ResourceManager.GetString(nameof(ToolbarPage_NewConfig), _resourceCulture);

        public static string ToolbarPage_NewProfile => ResourceManager.GetString(nameof(ToolbarPage_NewProfile), _resourceCulture);

        public static string ToolbarPage_OK => ResourceManager.GetString(nameof(ToolbarPage_OK), _resourceCulture);

        public static string ToolbarPage_Opacity => ResourceManager.GetString(nameof(ToolbarPage_Opacity), _resourceCulture);

        public static string ToolbarPage_RedStyle => ResourceManager.GetString(nameof(ToolbarPage_RedStyle), _resourceCulture);

        public static string ToolbarPage_RedStyleDesc => ResourceManager.GetString(nameof(ToolbarPage_RedStyleDesc), _resourceCulture);

        public static string ToolbarPage_QuickPaletteDisplayModeDesc => ResourceManager.GetString(nameof(ToolbarPage_QuickPaletteDisplayModeDesc), _resourceCulture);

        public static string ToolbarPage_ResetComponentSettings => ResourceManager.GetString(nameof(ToolbarPage_ResetComponentSettings), _resourceCulture);

        public static string ToolbarPage_ResetLayout => ResourceManager.GetString(nameof(ToolbarPage_ResetLayout), _resourceCulture);

        public static string ToolbarPage_Reverse => ResourceManager.GetString(nameof(ToolbarPage_Reverse), _resourceCulture);

        public static string ToolbarPage_Right => ResourceManager.GetString(nameof(ToolbarPage_Right), _resourceCulture);

        public static string ToolbarPage_Rule => ResourceManager.GetString(nameof(ToolbarPage_Rule), _resourceCulture);

        public static string ToolbarPage_SeparateBorder => ResourceManager.GetString(nameof(ToolbarPage_SeparateBorder), _resourceCulture);

        public static string ToolbarPage_SeparateBorderDesc => ResourceManager.GetString(nameof(ToolbarPage_SeparateBorderDesc), _resourceCulture);

        public static string ToolbarPage_Size => ResourceManager.GetString(nameof(ToolbarPage_Size), _resourceCulture);

        public static string ToolbarPage_Stretch => ResourceManager.GetString(nameof(ToolbarPage_Stretch), _resourceCulture);

        public static string ToolbarPage_Top => ResourceManager.GetString(nameof(ToolbarPage_Top), _resourceCulture);

        public static string ToolbarPage_VerticalAlignment => ResourceManager.GetString(nameof(ToolbarPage_VerticalAlignment), _resourceCulture);

        public static string FloatingBar_QuickPaletteMode => ResourceManager.GetString(nameof(FloatingBar_QuickPaletteMode), _resourceCulture);

        public static string FloatingBar_PenTipStyle => ResourceManager.GetString(nameof(FloatingBar_PenTipStyle), _resourceCulture);

        public static string FloatingBar_PenStyle_RealTime => ResourceManager.GetString(nameof(FloatingBar_PenStyle_RealTime), _resourceCulture);

        public static string FloatingBar_PenStyle_PointSet => ResourceManager.GetString(nameof(FloatingBar_PenStyle_PointSet), _resourceCulture);

        public static string FloatingBar_PenStyle_Velocity => ResourceManager.GetString(nameof(FloatingBar_PenStyle_Velocity), _resourceCulture);

        public static string FloatingBar_PenStyle_Off => ResourceManager.GetString(nameof(FloatingBar_PenStyle_Off), _resourceCulture);

        public static string FloatingBar_HighlighterOverlap => ResourceManager.GetString(nameof(FloatingBar_HighlighterOverlap), _resourceCulture);

        public static string FloatingBar_Opacity => ResourceManager.GetString(nameof(FloatingBar_Opacity), _resourceCulture);

        public static string FloatingBar_FadeDelay => ResourceManager.GetString(nameof(FloatingBar_FadeDelay), _resourceCulture);

        public static string FloatingBar_FadeSpeed => ResourceManager.GetString(nameof(FloatingBar_FadeSpeed), _resourceCulture);

        public static string FloatingBar_ColorThemeLight => ResourceManager.GetString(nameof(FloatingBar_ColorThemeLight), _resourceCulture);

        public static string BoardToolbarPage_AddComponent2 => ResourceManager.GetString(nameof(BoardToolbarPage_AddComponent2), _resourceCulture);

        public static string BoardToolbarPage_AddGroup => ResourceManager.GetString(nameof(BoardToolbarPage_AddGroup), _resourceCulture);

        public static string BoardToolbarPage_AddGroup2 => ResourceManager.GetString(nameof(BoardToolbarPage_AddGroup2), _resourceCulture);

        public static string BoardToolbarPage_Areas => ResourceManager.GetString(nameof(BoardToolbarPage_Areas), _resourceCulture);

        public static string BoardToolbarPage_AtLeastOneConfig => ResourceManager.GetString(nameof(BoardToolbarPage_AtLeastOneConfig), _resourceCulture);

        public static string BoardToolbarPage_CenterArea => ResourceManager.GetString(nameof(BoardToolbarPage_CenterArea), _resourceCulture);

        public static string BoardToolbarPage_ComponentLibrary => ResourceManager.GetString(nameof(BoardToolbarPage_ComponentLibrary), _resourceCulture);

        public static string BoardToolbarPage_ConfigProfiles => ResourceManager.GetString(nameof(BoardToolbarPage_ConfigProfiles), _resourceCulture);

        public static string BoardToolbarPage_ConfirmDeleteConfig => ResourceManager.GetString(nameof(BoardToolbarPage_ConfirmDeleteConfig), _resourceCulture);

        public static string BoardToolbarPage_DeleteProfile => ResourceManager.GetString(nameof(BoardToolbarPage_DeleteProfile), _resourceCulture);

        public static string BoardToolbarPage_DuplicateProfile => ResourceManager.GetString(nameof(BoardToolbarPage_DuplicateProfile), _resourceCulture);

        public static string BoardToolbarPage_EnterNewConfigName => ResourceManager.GetString(nameof(BoardToolbarPage_EnterNewConfigName), _resourceCulture);

        public static string BoardToolbarPage_LeftArea => ResourceManager.GetString(nameof(BoardToolbarPage_LeftArea), _resourceCulture);

        public static string BoardToolbarPage_NewGroupName => ResourceManager.GetString(nameof(BoardToolbarPage_NewGroupName), _resourceCulture);

        public static string BoardToolbarPage_NewProfile => ResourceManager.GetString(nameof(BoardToolbarPage_NewProfile), _resourceCulture);

        public static string BoardToolbarPage_ResetConfirm => ResourceManager.GetString(nameof(BoardToolbarPage_ResetConfirm), _resourceCulture);

        public static string BoardToolbarPage_ResetDefault => ResourceManager.GetString(nameof(BoardToolbarPage_ResetDefault), _resourceCulture);

        public static string BoardToolbarPage_RightArea => ResourceManager.GetString(nameof(BoardToolbarPage_RightArea), _resourceCulture);

        public static string BoardToolbarPage_AreaComponents => ResourceManager.GetString(nameof(BoardToolbarPage_AreaComponents), _resourceCulture);

        public static string BoardToolbarPage_AreaComponentsHint => ResourceManager.GetString(nameof(BoardToolbarPage_AreaComponentsHint), _resourceCulture);

        public static string BoardToolbarPage_AreaGroups => ResourceManager.GetString(nameof(BoardToolbarPage_AreaGroups), _resourceCulture);

        public static string BoardToolbarPage_Position => ResourceManager.GetString(nameof(BoardToolbarPage_Position), _resourceCulture);

        public static string BoardToolbarPage_PositionDesc => ResourceManager.GetString(nameof(BoardToolbarPage_PositionDesc), _resourceCulture);

        public static string BoardToolbarPage_PositionFirst => ResourceManager.GetString(nameof(BoardToolbarPage_PositionFirst), _resourceCulture);

        public static string BoardToolbarPage_PositionMiddle => ResourceManager.GetString(nameof(BoardToolbarPage_PositionMiddle), _resourceCulture);

        public static string BoardToolbarPage_PositionLast => ResourceManager.GetString(nameof(BoardToolbarPage_PositionLast), _resourceCulture);

        public static string BoardToolbarPage_PositionSingle => ResourceManager.GetString(nameof(BoardToolbarPage_PositionSingle), _resourceCulture);

        public static string BoardToolbarPage_MoveUp => ResourceManager.GetString(nameof(BoardToolbarPage_MoveUp), _resourceCulture);

        public static string BoardToolbarPage_MoveDown => ResourceManager.GetString(nameof(BoardToolbarPage_MoveDown), _resourceCulture);

        public static string BoardToolbarPage_GroupNavigation => ResourceManager.GetString(nameof(BoardToolbarPage_GroupNavigation), _resourceCulture);

        public static string BoardToolbarPage_GroupVideoBooth => ResourceManager.GetString(nameof(BoardToolbarPage_GroupVideoBooth), _resourceCulture);

        public static string BoardToolbarPage_GroupGesture => ResourceManager.GetString(nameof(BoardToolbarPage_GroupGesture), _resourceCulture);

        public static string BoardToolbarPage_GroupTools => ResourceManager.GetString(nameof(BoardToolbarPage_GroupTools), _resourceCulture);

        public static string BoardToolbarPage_GroupSystem => ResourceManager.GetString(nameof(BoardToolbarPage_GroupSystem), _resourceCulture);

        public static string BoardToolbarPage_GroupAddPage => ResourceManager.GetString(nameof(BoardToolbarPage_GroupAddPage), _resourceCulture);

        public static string BoardToolbarPage_Title => ResourceManager.GetString(nameof(BoardToolbarPage_Title), _resourceCulture);

        public static string FloatingBar_MiniWhiteboard => ResourceManager.GetString(nameof(FloatingBar_MiniWhiteboard), _resourceCulture);

        public static string MiniWhiteboard_Undo => ResourceManager.GetString(nameof(MiniWhiteboard_Undo), _resourceCulture);

        public static string MiniWhiteboard_Redo => ResourceManager.GetString(nameof(MiniWhiteboard_Redo), _resourceCulture);

        public static string MiniWhiteboard_Clear => ResourceManager.GetString(nameof(MiniWhiteboard_Clear), _resourceCulture);

        public static string MiniWhiteboard_NewPage => ResourceManager.GetString(nameof(MiniWhiteboard_NewPage), _resourceCulture);

        public static string MiniWhiteboard_DeletePage => ResourceManager.GetString(nameof(MiniWhiteboard_DeletePage), _resourceCulture);

        public static string MiniWhiteboard_PageInfo => ResourceManager.GetString(nameof(MiniWhiteboard_PageInfo), _resourceCulture);

        public static string MiniWhiteboard_Pen => ResourceManager.GetString(nameof(MiniWhiteboard_Pen), _resourceCulture);

        public static string MiniWhiteboard_Eraser => ResourceManager.GetString(nameof(MiniWhiteboard_Eraser), _resourceCulture);

        public static string MiniWhiteboard_Settings_Enable => ResourceManager.GetString(nameof(MiniWhiteboard_Settings_Enable), _resourceCulture);

        public static string MiniWhiteboard_Settings_SyncPPT => ResourceManager.GetString(nameof(MiniWhiteboard_Settings_SyncPPT), _resourceCulture);

        public static string MiniWhiteboard_Settings_DefaultSize => ResourceManager.GetString(nameof(MiniWhiteboard_Settings_DefaultSize), _resourceCulture);

        public static string MiniWhiteboard_Settings_Opacity => ResourceManager.GetString(nameof(MiniWhiteboard_Settings_Opacity), _resourceCulture);
    }
}