//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from FriendlyLinksStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class FriendlyLinksStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.FriendlyLinksStrings", typeof(FriendlyLinksStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string FriendlyLinks_CjikSponsorDescription => ResourceManager.GetString(nameof(FriendlyLinks_CjikSponsorDescription), _resourceCulture);

        public static string FriendlyLinks_FriendsSectionTitle => ResourceManager.GetString(nameof(FriendlyLinks_FriendsSectionTitle), _resourceCulture);

        public static string FriendlyLinks_DeveloperCloudDescription => ResourceManager.GetString(nameof(FriendlyLinks_DeveloperCloudDescription), _resourceCulture);

        public static string FriendlyLinks_InkeysDescription => ResourceManager.GetString(nameof(FriendlyLinks_InkeysDescription), _resourceCulture);

        public static string FriendlyLinks_NamePickerDescription => ResourceManager.GetString(nameof(FriendlyLinks_NamePickerDescription), _resourceCulture);

        public static string FriendlyLinks_Sponsor => ResourceManager.GetString(nameof(FriendlyLinks_Sponsor), _resourceCulture);

        public static string FriendlyLinks_SponsorSectionTitle => ResourceManager.GetString(nameof(FriendlyLinks_SponsorSectionTitle), _resourceCulture);

        public static string FriendlyLinks_Title => ResourceManager.GetString(nameof(FriendlyLinks_Title), _resourceCulture);

        public static string FriendlyLinks_Visit => ResourceManager.GetString(nameof(FriendlyLinks_Visit), _resourceCulture);
    }
}