//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from GeometryStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class GeometryStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.GeometryStrings", typeof(GeometryStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string DrawArrow => ResourceManager.GetString(nameof(DrawArrow), _resourceCulture);

        public static string DrawCenteredCircle => ResourceManager.GetString(nameof(DrawCenteredCircle), _resourceCulture);

        public static string DrawCenteredDashedCircle => ResourceManager.GetString(nameof(DrawCenteredDashedCircle), _resourceCulture);

        public static string DrawCenteredEllipse => ResourceManager.GetString(nameof(DrawCenteredEllipse), _resourceCulture);

        public static string DrawCenteredSquare => ResourceManager.GetString(nameof(DrawCenteredSquare), _resourceCulture);

        public static string DrawCone => ResourceManager.GetString(nameof(DrawCone), _resourceCulture);

        public static string DrawCoordinate1 => ResourceManager.GetString(nameof(DrawCoordinate1), _resourceCulture);

        public static string DrawCoordinate2 => ResourceManager.GetString(nameof(DrawCoordinate2), _resourceCulture);

        public static string DrawCoordinate3 => ResourceManager.GetString(nameof(DrawCoordinate3), _resourceCulture);

        public static string DrawCoordinate4 => ResourceManager.GetString(nameof(DrawCoordinate4), _resourceCulture);

        public static string DrawCoordinate5 => ResourceManager.GetString(nameof(DrawCoordinate5), _resourceCulture);

        public static string DrawCuboid => ResourceManager.GetString(nameof(DrawCuboid), _resourceCulture);

        public static string DrawCylinder => ResourceManager.GetString(nameof(DrawCylinder), _resourceCulture);

        public static string DrawDashedLine => ResourceManager.GetString(nameof(DrawDashedLine), _resourceCulture);

        public static string DrawDottedLine => ResourceManager.GetString(nameof(DrawDottedLine), _resourceCulture);

        public static string DrawHyperbola => ResourceManager.GetString(nameof(DrawHyperbola), _resourceCulture);

        public static string DrawHyperbolaWithFocal => ResourceManager.GetString(nameof(DrawHyperbolaWithFocal), _resourceCulture);

        public static string DrawLine => ResourceManager.GetString(nameof(DrawLine), _resourceCulture);

        public static string DrawParabola => ResourceManager.GetString(nameof(DrawParabola), _resourceCulture);

        public static string DrawParabola2 => ResourceManager.GetString(nameof(DrawParabola2), _resourceCulture);

        public static string DrawParabolaWithFocal => ResourceManager.GetString(nameof(DrawParabolaWithFocal), _resourceCulture);

        public static string DrawParallelLines => ResourceManager.GetString(nameof(DrawParallelLines), _resourceCulture);

        public static string DrawSquare => ResourceManager.GetString(nameof(DrawSquare), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);
    }
}