//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from GestureStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class GestureStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.GestureStrings", typeof(GestureStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Gesture_AllowRotateScale => ResourceManager.GetString(nameof(Gesture_AllowRotateScale), _resourceCulture);

        public static string Gesture_AllowRotateScaleHint => ResourceManager.GetString(nameof(Gesture_AllowRotateScaleHint), _resourceCulture);

        public static string Gesture_EnablePalmEraser => ResourceManager.GetString(nameof(Gesture_EnablePalmEraser), _resourceCulture);

        public static string Gesture_PalmHint => ResourceManager.GetString(nameof(Gesture_PalmHint), _resourceCulture);

        public static string Gesture_PalmSensitivity => ResourceManager.GetString(nameof(Gesture_PalmSensitivity), _resourceCulture);

        public static string Gesture_PalmSensitivityHigh => ResourceManager.GetString(nameof(Gesture_PalmSensitivityHigh), _resourceCulture);

        public static string Gesture_PalmSensitivityLow => ResourceManager.GetString(nameof(Gesture_PalmSensitivityLow), _resourceCulture);

        public static string Gesture_PalmSensitivityMedium => ResourceManager.GetString(nameof(Gesture_PalmSensitivityMedium), _resourceCulture);

        public static string Gesture_Title => ResourceManager.GetString(nameof(Gesture_Title), _resourceCulture);
    }
}