//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from HotkeyStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class HotkeyStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.HotkeyStrings", typeof(HotkeyStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Hotkey_InfoBarTitle => ResourceManager.GetString(nameof(Hotkey_InfoBarTitle), _resourceCulture);

        public static string Hotkey_InfoBarMessage => ResourceManager.GetString(nameof(Hotkey_InfoBarMessage), _resourceCulture);

        public static string Hotkey_MouseMode => ResourceManager.GetString(nameof(Hotkey_MouseMode), _resourceCulture);

        public static string Hotkey_EnableHotkeysInMouseMode => ResourceManager.GetString(nameof(Hotkey_EnableHotkeysInMouseMode), _resourceCulture);

        public static string Hotkey_EnableHotkeysInMouseModeHint => ResourceManager.GetString(nameof(Hotkey_EnableHotkeysInMouseModeHint), _resourceCulture);

        public static string Hotkey_BasicOperations => ResourceManager.GetString(nameof(Hotkey_BasicOperations), _resourceCulture);

        public static string Hotkey_UndoDesc => ResourceManager.GetString(nameof(Hotkey_UndoDesc), _resourceCulture);

        public static string Hotkey_RedoDesc => ResourceManager.GetString(nameof(Hotkey_RedoDesc), _resourceCulture);

        public static string Hotkey_ClearDesc => ResourceManager.GetString(nameof(Hotkey_ClearDesc), _resourceCulture);

        public static string Hotkey_Paste => ResourceManager.GetString(nameof(Hotkey_Paste), _resourceCulture);

        public static string Hotkey_PasteDesc => ResourceManager.GetString(nameof(Hotkey_PasteDesc), _resourceCulture);

        public static string Hotkey_ToolSwitch => ResourceManager.GetString(nameof(Hotkey_ToolSwitch), _resourceCulture);

        public static string Hotkey_SelectTool => ResourceManager.GetString(nameof(Hotkey_SelectTool), _resourceCulture);

        public static string Hotkey_SelectToolDesc => ResourceManager.GetString(nameof(Hotkey_SelectToolDesc), _resourceCulture);

        public static string Hotkey_DrawTool => ResourceManager.GetString(nameof(Hotkey_DrawTool), _resourceCulture);

        public static string Hotkey_DrawToolDesc => ResourceManager.GetString(nameof(Hotkey_DrawToolDesc), _resourceCulture);

        public static string Hotkey_EraserTool => ResourceManager.GetString(nameof(Hotkey_EraserTool), _resourceCulture);

        public static string Hotkey_EraserToolDesc => ResourceManager.GetString(nameof(Hotkey_EraserToolDesc), _resourceCulture);

        public static string Hotkey_BlackboardTool => ResourceManager.GetString(nameof(Hotkey_BlackboardTool), _resourceCulture);

        public static string Hotkey_BlackboardToolDesc => ResourceManager.GetString(nameof(Hotkey_BlackboardToolDesc), _resourceCulture);

        public static string Hotkey_QuitDrawTool => ResourceManager.GetString(nameof(Hotkey_QuitDrawTool), _resourceCulture);

        public static string Hotkey_QuitDrawToolDesc => ResourceManager.GetString(nameof(Hotkey_QuitDrawToolDesc), _resourceCulture);

        public static string Hotkey_PenSettings => ResourceManager.GetString(nameof(Hotkey_PenSettings), _resourceCulture);

        public static string Hotkey_Pen1 => ResourceManager.GetString(nameof(Hotkey_Pen1), _resourceCulture);

        public static string Hotkey_Pen1Desc => ResourceManager.GetString(nameof(Hotkey_Pen1Desc), _resourceCulture);

        public static string Hotkey_Pen2 => ResourceManager.GetString(nameof(Hotkey_Pen2), _resourceCulture);

        public static string Hotkey_Pen2Desc => ResourceManager.GetString(nameof(Hotkey_Pen2Desc), _resourceCulture);

        public static string Hotkey_Pen3 => ResourceManager.GetString(nameof(Hotkey_Pen3), _resourceCulture);

        public static string Hotkey_Pen3Desc => ResourceManager.GetString(nameof(Hotkey_Pen3Desc), _resourceCulture);

        public static string Hotkey_Pen4 => ResourceManager.GetString(nameof(Hotkey_Pen4), _resourceCulture);

        public static string Hotkey_Pen4Desc => ResourceManager.GetString(nameof(Hotkey_Pen4Desc), _resourceCulture);

        public static string Hotkey_Pen5 => ResourceManager.GetString(nameof(Hotkey_Pen5), _resourceCulture);

        public static string Hotkey_Pen5Desc => ResourceManager.GetString(nameof(Hotkey_Pen5Desc), _resourceCulture);

        public static string Hotkey_FunctionHotkeys => ResourceManager.GetString(nameof(Hotkey_FunctionHotkeys), _resourceCulture);

        public static string Hotkey_DrawLine => ResourceManager.GetString(nameof(Hotkey_DrawLine), _resourceCulture);

        public static string Hotkey_DrawLineDesc => ResourceManager.GetString(nameof(Hotkey_DrawLineDesc), _resourceCulture);

        public static string Hotkey_ScreenshotDesc => ResourceManager.GetString(nameof(Hotkey_ScreenshotDesc), _resourceCulture);

        public static string Hotkey_QuickDraw => ResourceManager.GetString(nameof(Hotkey_QuickDraw), _resourceCulture);

        public static string Hotkey_QuickDrawDesc => ResourceManager.GetString(nameof(Hotkey_QuickDrawDesc), _resourceCulture);

        public static string Hotkey_HideDesc => ResourceManager.GetString(nameof(Hotkey_HideDesc), _resourceCulture);

        public static string Hotkey_ExitDesc => ResourceManager.GetString(nameof(Hotkey_ExitDesc), _resourceCulture);

        public static string Hotkey_ResetToDefault => ResourceManager.GetString(nameof(Hotkey_ResetToDefault), _resourceCulture);

        public static string Hotkey_SaveSettings => ResourceManager.GetString(nameof(Hotkey_SaveSettings), _resourceCulture);

        public static string Hotkey_ManagerNotInit => ResourceManager.GetString(nameof(Hotkey_ManagerNotInit), _resourceCulture);

        public static string Hotkey_Error => ResourceManager.GetString(nameof(Hotkey_Error), _resourceCulture);

        public static string Hotkey_ConflictMessage => ResourceManager.GetString(nameof(Hotkey_ConflictMessage), _resourceCulture);

        public static string Hotkey_ConflictTitle => ResourceManager.GetString(nameof(Hotkey_ConflictTitle), _resourceCulture);

        public static string Hotkey_ConfirmResetMessage => ResourceManager.GetString(nameof(Hotkey_ConfirmResetMessage), _resourceCulture);

        public static string Hotkey_ConfirmResetTitle => ResourceManager.GetString(nameof(Hotkey_ConfirmResetTitle), _resourceCulture);

        public static string Hotkey_ResetCompleteMessage => ResourceManager.GetString(nameof(Hotkey_ResetCompleteMessage), _resourceCulture);

        public static string Hotkey_ResetCompleteTitle => ResourceManager.GetString(nameof(Hotkey_ResetCompleteTitle), _resourceCulture);

        public static string Hotkey_ResetErrorMessage => ResourceManager.GetString(nameof(Hotkey_ResetErrorMessage), _resourceCulture);

        public static string Hotkey_SaveSuccessMessage => ResourceManager.GetString(nameof(Hotkey_SaveSuccessMessage), _resourceCulture);

        public static string Hotkey_SaveSuccessTitle => ResourceManager.GetString(nameof(Hotkey_SaveSuccessTitle), _resourceCulture);

        public static string Hotkey_SaveErrorMessage => ResourceManager.GetString(nameof(Hotkey_SaveErrorMessage), _resourceCulture);
    }
}
