//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from MainStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class MainStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.MainStrings", typeof(MainStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Main_Tray_HideWindow => ResourceManager.GetString(nameof(Main_Tray_HideWindow), _resourceCulture);

        public static string Main_Tray_ShowWindow => ResourceManager.GetString(nameof(Main_Tray_ShowWindow), _resourceCulture);

        public static string Main_Tray_DisableHotkeys => ResourceManager.GetString(nameof(Main_Tray_DisableHotkeys), _resourceCulture);

        public static string Main_Tray_SwitchFoldMode => ResourceManager.GetString(nameof(Main_Tray_SwitchFoldMode), _resourceCulture);
    }
}
