//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from NavStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class NavStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.NavStrings", typeof(NavStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Nav_Advanced => ResourceManager.GetString(nameof(Nav_Advanced), _resourceCulture);

        public static string Nav_Advanced_Settings => ResourceManager.GetString(nameof(Nav_Advanced_Settings), _resourceCulture);

        public static string Nav_Automation_Settings => ResourceManager.GetString(nameof(Nav_Automation_Settings), _resourceCulture);

        public static string Nav_FriendlyLinks => ResourceManager.GetString(nameof(Nav_FriendlyLinks), _resourceCulture);

        public static string Nav_Plugins => ResourceManager.GetString(nameof(Nav_Plugins), _resourceCulture);

        public static string Nav_PPT_Settings => ResourceManager.GetString(nameof(Nav_PPT_Settings), _resourceCulture);

        public static string Nav_Shortcuts => ResourceManager.GetString(nameof(Nav_Shortcuts), _resourceCulture);

        public static string Nav_Startup => ResourceManager.GetString(nameof(Nav_Startup), _resourceCulture);

        public static string Nav_Theme_Settings => ResourceManager.GetString(nameof(Nav_Theme_Settings), _resourceCulture);

        public static string Settings_ModeDesc => ResourceManager.GetString(nameof(Settings_ModeDesc), _resourceCulture);

        public static string Settings_ModeDesc_1 => ResourceManager.GetString(nameof(Settings_ModeDesc_1), _resourceCulture);

        public static string Settings_Nav_Hotkey_Tooltip => ResourceManager.GetString(nameof(Settings_Nav_Hotkey_Tooltip), _resourceCulture);

        public static string Settings_Nav_Security => ResourceManager.GetString(nameof(Settings_Nav_Security), _resourceCulture);

        public static string Settings_Nav_Security_Tooltip => ResourceManager.GetString(nameof(Settings_Nav_Security_Tooltip), _resourceCulture);

        public static string Settings_Plugins => ResourceManager.GetString(nameof(Settings_Plugins), _resourceCulture);

        public static string Settings_Title => ResourceManager.GetString(nameof(Settings_Title), _resourceCulture);

        public static string Nav_SettingsWindow_Title => ResourceManager.GetString(nameof(Nav_SettingsWindow_Title), _resourceCulture);

        public static string Nav_AppSettings => ResourceManager.GetString(nameof(Nav_AppSettings), _resourceCulture);

        public static string Nav_SearchSettings => ResourceManager.GetString(nameof(Nav_SearchSettings), _resourceCulture);

        public static string Nav_Home => ResourceManager.GetString(nameof(Nav_Home), _resourceCulture);

        public static string Nav_Home_Tooltip => ResourceManager.GetString(nameof(Nav_Home_Tooltip), _resourceCulture);

        public static string Nav_ICCSettings => ResourceManager.GetString(nameof(Nav_ICCSettings), _resourceCulture);

        public static string Nav_Basic => ResourceManager.GetString(nameof(Nav_Basic), _resourceCulture);

        public static string Nav_General => ResourceManager.GetString(nameof(Nav_General), _resourceCulture);

        public static string Nav_General_Tooltip => ResourceManager.GetString(nameof(Nav_General_Tooltip), _resourceCulture);

        public static string Nav_Startup_Tooltip => ResourceManager.GetString(nameof(Nav_Startup_Tooltip), _resourceCulture);

        public static string Nav_Clock => ResourceManager.GetString(nameof(Nav_Clock), _resourceCulture);

        public static string Nav_Clock_Tooltip => ResourceManager.GetString(nameof(Nav_Clock_Tooltip), _resourceCulture);

        public static string Nav_ToolbarComponents => ResourceManager.GetString(nameof(Nav_ToolbarComponents), _resourceCulture);

        public static string Nav_ToolbarComponents_Tooltip => ResourceManager.GetString(nameof(Nav_ToolbarComponents_Tooltip), _resourceCulture);

        public static string Nav_ToolbarAppearance => ResourceManager.GetString(nameof(Nav_ToolbarAppearance), _resourceCulture);

        public static string Nav_ToolbarAppearance_Tooltip => ResourceManager.GetString(nameof(Nav_ToolbarAppearance_Tooltip), _resourceCulture);

        public static string Nav_Basic_Tooltip => ResourceManager.GetString(nameof(Nav_Basic_Tooltip), _resourceCulture);

        public static string Nav_Privacy => ResourceManager.GetString(nameof(Nav_Privacy), _resourceCulture);

        public static string Nav_Privacy_Tooltip => ResourceManager.GetString(nameof(Nav_Privacy_Tooltip), _resourceCulture);

        public static string Nav_MainInterface => ResourceManager.GetString(nameof(Nav_MainInterface), _resourceCulture);

        public static string Nav_MainInterface_Tooltip => ResourceManager.GetString(nameof(Nav_MainInterface_Tooltip), _resourceCulture);

        public static string Nav_Window => ResourceManager.GetString(nameof(Nav_Window), _resourceCulture);

        public static string Nav_Window_Tooltip => ResourceManager.GetString(nameof(Nav_Window_Tooltip), _resourceCulture);

        public static string Nav_Toolbar => ResourceManager.GetString(nameof(Nav_Toolbar), _resourceCulture);

        public static string Nav_Toolbar_Tooltip => ResourceManager.GetString(nameof(Nav_Toolbar_Tooltip), _resourceCulture);

        public static string Nav_BoardToolbar => ResourceManager.GetString(nameof(Nav_BoardToolbar), _resourceCulture);

        public static string Nav_BoardToolbar_Tooltip => ResourceManager.GetString(nameof(Nav_BoardToolbar_Tooltip), _resourceCulture);

        public static string Nav_Board => ResourceManager.GetString(nameof(Nav_Board), _resourceCulture);

        public static string Nav_Board_Tooltip => ResourceManager.GetString(nameof(Nav_Board_Tooltip), _resourceCulture);

        public static string Nav_BoardComponents => ResourceManager.GetString(nameof(Nav_BoardComponents), _resourceCulture);

        public static string Nav_BoardComponents_Tooltip => ResourceManager.GetString(nameof(Nav_BoardComponents_Tooltip), _resourceCulture);

        public static string Nav_BoardAppearance => ResourceManager.GetString(nameof(Nav_BoardAppearance), _resourceCulture);

        public static string Nav_BoardAppearance_Tooltip => ResourceManager.GetString(nameof(Nav_BoardAppearance_Tooltip), _resourceCulture);

        public static string Nav_ToolbarMenu => ResourceManager.GetString(nameof(Nav_ToolbarMenu), _resourceCulture);

        public static string Nav_ToolbarMenu_Tooltip => ResourceManager.GetString(nameof(Nav_ToolbarMenu_Tooltip), _resourceCulture);

        public static string Nav_BoardMenu => ResourceManager.GetString(nameof(Nav_BoardMenu), _resourceCulture);

        public static string Nav_BoardMenu_Tooltip => ResourceManager.GetString(nameof(Nav_BoardMenu_Tooltip), _resourceCulture);

        public static string Nav_CanvasAndInk_Tooltip => ResourceManager.GetString(nameof(Nav_CanvasAndInk_Tooltip), _resourceCulture);

        public static string Nav_Canvas_Tooltip => ResourceManager.GetString(nameof(Nav_Canvas_Tooltip), _resourceCulture);

        public static string Nav_InkRecognition_Tooltip => ResourceManager.GetString(nameof(Nav_InkRecognition_Tooltip), _resourceCulture);

        public static string Nav_PPT_Tooltip => ResourceManager.GetString(nameof(Nav_PPT_Tooltip), _resourceCulture);

        public static string Nav_Update_Tooltip => ResourceManager.GetString(nameof(Nav_Update_Tooltip), _resourceCulture);

        public static string Nav_RandomDraw_Tooltip => ResourceManager.GetString(nameof(Nav_RandomDraw_Tooltip), _resourceCulture);

        public static string Nav_PluginSettings => ResourceManager.GetString(nameof(Nav_PluginSettings), _resourceCulture);

        public static string Nav_AboutInkCanvas => ResourceManager.GetString(nameof(Nav_AboutInkCanvas), _resourceCulture);

        public static string Nav_NavigateError => ResourceManager.GetString(nameof(Nav_NavigateError), _resourceCulture);

        public static string Nav_Error => ResourceManager.GetString(nameof(Nav_Error), _resourceCulture);

        public static string Nav_PluginSettingsFormat => ResourceManager.GetString(nameof(Nav_PluginSettingsFormat), _resourceCulture);

        public static string Nav_IndexBuildFailed => ResourceManager.GetString(nameof(Nav_IndexBuildFailed), _resourceCulture);

        public static string Nav_LoadPluginSettingsFailed => ResourceManager.GetString(nameof(Nav_LoadPluginSettingsFailed), _resourceCulture);

        public static string Nav_PreloadPageFailed => ResourceManager.GetString(nameof(Nav_PreloadPageFailed), _resourceCulture);

        public static string Nav_PreloadPagesFailed => ResourceManager.GetString(nameof(Nav_PreloadPagesFailed), _resourceCulture);

        public static string Settings_Description => ResourceManager.GetString(nameof(Settings_Description), _resourceCulture);

        public static string Nav_Performance => ResourceManager.GetString(nameof(Nav_Performance), _resourceCulture);

        public static string Nav_Performance_Tooltip => ResourceManager.GetString(nameof(Nav_Performance_Tooltip), _resourceCulture);

        public static string Nav_Display => ResourceManager.GetString(nameof(Nav_Display), _resourceCulture);

        public static string Nav_Display_Tooltip => ResourceManager.GetString(nameof(Nav_Display_Tooltip), _resourceCulture);

        public static string Nav_ScreenTouch => ResourceManager.GetString(nameof(Nav_ScreenTouch), _resourceCulture);

        public static string Nav_ScreenTouch_Tooltip => ResourceManager.GetString(nameof(Nav_ScreenTouch_Tooltip), _resourceCulture);

        public static string Nav_PrivacyAndSecurity => ResourceManager.GetString(nameof(Nav_PrivacyAndSecurity), _resourceCulture);

        public static string Nav_PrivacyAndSecurity_Tooltip => ResourceManager.GetString(nameof(Nav_PrivacyAndSecurity_Tooltip), _resourceCulture);

        public static string Nav_Personalization => ResourceManager.GetString(nameof(Nav_Personalization), _resourceCulture);

        public static string Nav_Personalization_Tooltip => ResourceManager.GetString(nameof(Nav_Personalization_Tooltip), _resourceCulture);

        public static string Nav_LinkageControls => ResourceManager.GetString(nameof(Nav_LinkageControls), _resourceCulture);

        public static string Nav_LinkageControls_Tooltip => ResourceManager.GetString(nameof(Nav_LinkageControls_Tooltip), _resourceCulture);

        public static string Nav_Linkage => ResourceManager.GetString(nameof(Nav_Linkage), _resourceCulture);

        public static string Nav_Linkage_Tooltip => ResourceManager.GetString(nameof(Nav_Linkage_Tooltip), _resourceCulture);

        public static string Nav_FloatingBar => ResourceManager.GetString(nameof(Nav_FloatingBar), _resourceCulture);

        public static string Nav_FloatingBar_Tooltip => ResourceManager.GetString(nameof(Nav_FloatingBar_Tooltip), _resourceCulture);

        public static string Nav_BoardPage => ResourceManager.GetString(nameof(Nav_BoardPage), _resourceCulture);

        public static string Nav_BoardPage_Tooltip => ResourceManager.GetString(nameof(Nav_BoardPage_Tooltip), _resourceCulture);

        public static string Nav_BoardCanvas => ResourceManager.GetString(nameof(Nav_BoardCanvas), _resourceCulture);

        public static string Nav_BoardCanvas_Tooltip => ResourceManager.GetString(nameof(Nav_BoardCanvas_Tooltip), _resourceCulture);

        public static string Nav_Booth => ResourceManager.GetString(nameof(Nav_Booth), _resourceCulture);

        public static string Nav_Booth_Tooltip => ResourceManager.GetString(nameof(Nav_Booth_Tooltip), _resourceCulture);

        public static string Nav_RollCall => ResourceManager.GetString(nameof(Nav_RollCall), _resourceCulture);

        public static string Nav_RollCall_Tooltip => ResourceManager.GetString(nameof(Nav_RollCall_Tooltip), _resourceCulture);

        public static string Nav_Timer => ResourceManager.GetString(nameof(Nav_Timer), _resourceCulture);

        public static string Nav_Timer_Tooltip => ResourceManager.GetString(nameof(Nav_Timer_Tooltip), _resourceCulture);

        public static string Nav_Magnifier => ResourceManager.GetString(nameof(Nav_Magnifier), _resourceCulture);

        public static string Nav_Magnifier_Tooltip => ResourceManager.GetString(nameof(Nav_Magnifier_Tooltip), _resourceCulture);

        public static string Nav_NotificationCenter => ResourceManager.GetString(nameof(Nav_NotificationCenter), _resourceCulture);

        public static string Nav_NotificationCenter_Tooltip => ResourceManager.GetString(nameof(Nav_NotificationCenter_Tooltip), _resourceCulture);

        public static string Nav_AutoFold => ResourceManager.GetString(nameof(Nav_AutoFold), _resourceCulture);

        public static string Nav_AutoFold_Tooltip => ResourceManager.GetString(nameof(Nav_AutoFold_Tooltip), _resourceCulture);

        public static string Nav_PPTSync => ResourceManager.GetString(nameof(Nav_PPTSync), _resourceCulture);

        public static string Nav_PPTSync_Tooltip => ResourceManager.GetString(nameof(Nav_PPTSync_Tooltip), _resourceCulture);

        public static string Nav_Config => ResourceManager.GetString(nameof(Nav_Config), _resourceCulture);

        public static string Nav_Config_Tooltip => ResourceManager.GetString(nameof(Nav_Config_Tooltip), _resourceCulture);

        public static string Nav_Sync => ResourceManager.GetString(nameof(Nav_Sync), _resourceCulture);

        public static string Nav_Sync_Tooltip => ResourceManager.GetString(nameof(Nav_Sync_Tooltip), _resourceCulture);

        public static string Nav_Storage => ResourceManager.GetString(nameof(Nav_Storage), _resourceCulture);

        public static string Nav_Storage_Tooltip => ResourceManager.GetString(nameof(Nav_Storage_Tooltip), _resourceCulture);

        public static string Nav_Favourites => ResourceManager.GetString(nameof(Nav_Favourites), _resourceCulture);

        public static string Nav_Favourites_Tooltip => ResourceManager.GetString(nameof(Nav_Favourites_Tooltip), _resourceCulture);

        public static string Nav_Favourites_Empty => ResourceManager.GetString(nameof(Nav_Favourites_Empty), _resourceCulture);

        public static string Nav_Favourites_LocatedIn => ResourceManager.GetString(nameof(Nav_Favourites_LocatedIn), _resourceCulture);
    }
}