//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from PerformanceStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class PerformanceStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.PerformanceStrings", typeof(PerformanceStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);

        public static string EnableMonitoring => ResourceManager.GetString(nameof(EnableMonitoring), _resourceCulture);

        public static string EnableMonitoringHint => ResourceManager.GetString(nameof(EnableMonitoringHint), _resourceCulture);

        public static string CurrentSession => ResourceManager.GetString(nameof(CurrentSession), _resourceCulture);

        public static string CpuUsage => ResourceManager.GetString(nameof(CpuUsage), _resourceCulture);

        public static string SystemCpuUsage => ResourceManager.GetString(nameof(SystemCpuUsage), _resourceCulture);

        public static string MemoryUsage => ResourceManager.GetString(nameof(MemoryUsage), _resourceCulture);

        public static string MonitoringInactive => ResourceManager.GetString(nameof(MonitoringInactive), _resourceCulture);

        public static string MonitoringActive => ResourceManager.GetString(nameof(MonitoringActive), _resourceCulture);

        public static string HistorySection => ResourceManager.GetString(nameof(HistorySection), _resourceCulture);

        public static string HistoryHint => ResourceManager.GetString(nameof(HistoryHint), _resourceCulture);

        public static string NoHistory => ResourceManager.GetString(nameof(NoHistory), _resourceCulture);

        public static string HistoryRunCount => ResourceManager.GetString(nameof(HistoryRunCount), _resourceCulture);

        public static string AvgCpuLabel => ResourceManager.GetString(nameof(AvgCpuLabel), _resourceCulture);

        public static string AvgMemoryLabel => ResourceManager.GetString(nameof(AvgMemoryLabel), _resourceCulture);

        public static string PeakCpuLabel => ResourceManager.GetString(nameof(PeakCpuLabel), _resourceCulture);

        public static string PeakMemoryLabel => ResourceManager.GetString(nameof(PeakMemoryLabel), _resourceCulture);

        public static string ClearHistory => ResourceManager.GetString(nameof(ClearHistory), _resourceCulture);

        public static string ClearHistoryConfirm => ResourceManager.GetString(nameof(ClearHistoryConfirm), _resourceCulture);

        public static string DeviceScoreSection => ResourceManager.GetString(nameof(DeviceScoreSection), _resourceCulture);

        public static string DeviceScoreHint => ResourceManager.GetString(nameof(DeviceScoreHint), _resourceCulture);

        public static string RunDeviceTest => ResourceManager.GetString(nameof(RunDeviceTest), _resourceCulture);

        public static string DeviceScoreResult => ResourceManager.GetString(nameof(DeviceScoreResult), _resourceCulture);

        public static string DeviceScoreExcellent => ResourceManager.GetString(nameof(DeviceScoreExcellent), _resourceCulture);

        public static string DeviceScoreGood => ResourceManager.GetString(nameof(DeviceScoreGood), _resourceCulture);

        public static string DeviceScoreFair => ResourceManager.GetString(nameof(DeviceScoreFair), _resourceCulture);

        public static string DeviceScorePoor => ResourceManager.GetString(nameof(DeviceScorePoor), _resourceCulture);

        public static string DeviceScoreUnknown => ResourceManager.GetString(nameof(DeviceScoreUnknown), _resourceCulture);

        public static string CpuScore => ResourceManager.GetString(nameof(CpuScore), _resourceCulture);

        public static string MemoryScore => ResourceManager.GetString(nameof(MemoryScore), _resourceCulture);

        public static string DiskScore => ResourceManager.GetString(nameof(DiskScore), _resourceCulture);

        public static string LastTestTime => ResourceManager.GetString(nameof(LastTestTime), _resourceCulture);

        public static string TestInProgress => ResourceManager.GetString(nameof(TestInProgress), _resourceCulture);

        public static string InkSmoothingSection => ResourceManager.GetString(nameof(InkSmoothingSection), _resourceCulture);

        public static string InkSmoothingHint => ResourceManager.GetString(nameof(InkSmoothingHint), _resourceCulture);

        public static string InkSmoothingInactive => ResourceManager.GetString(nameof(InkSmoothingInactive), _resourceCulture);

        public static string InkSmoothingAvgTotal => ResourceManager.GetString(nameof(InkSmoothingAvgTotal), _resourceCulture);

        public static string InkSmoothingMaxTotal => ResourceManager.GetString(nameof(InkSmoothingMaxTotal), _resourceCulture);

        public static string InkSmoothingAvgBezier => ResourceManager.GetString(nameof(InkSmoothingAvgBezier), _resourceCulture);

        public static string InkSmoothingAvgResample => ResourceManager.GetString(nameof(InkSmoothingAvgResample), _resourceCulture);

        public static string InkSmoothingAvgInputPoints => ResourceManager.GetString(nameof(InkSmoothingAvgInputPoints), _resourceCulture);

        public static string InkSmoothingAvgOutputPoints => ResourceManager.GetString(nameof(InkSmoothingAvgOutputPoints), _resourceCulture);

        public static string InkSmoothingSampleCount => ResourceManager.GetString(nameof(InkSmoothingSampleCount), _resourceCulture);
    }
}
