//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from PluginStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class PluginStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.PluginStrings", typeof(PluginStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Plugin_Title => ResourceManager.GetString(nameof(Plugin_Title), _resourceCulture);

        public static string Plugin_Loading => ResourceManager.GetString(nameof(Plugin_Loading), _resourceCulture);

        public static string Plugin_LoadedCount => ResourceManager.GetString(nameof(Plugin_LoadedCount), _resourceCulture);

        public static string Plugin_NoPlugins => ResourceManager.GetString(nameof(Plugin_NoPlugins), _resourceCulture);

        public static string Plugin_LoadError => ResourceManager.GetString(nameof(Plugin_LoadError), _resourceCulture);

        public static string Plugin_Author => ResourceManager.GetString(nameof(Plugin_Author), _resourceCulture);

        public static string Plugin_Settings => ResourceManager.GetString(nameof(Plugin_Settings), _resourceCulture);
    }
}
