//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from PopupStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class PopupStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.PopupStrings", typeof(PopupStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Popup_PenTipStyle => ResourceManager.GetString(nameof(Popup_PenTipStyle), _resourceCulture);

        public static string Popup_PenTipRealtime => ResourceManager.GetString(nameof(Popup_PenTipRealtime), _resourceCulture);

        public static string Popup_PenTipByPointSet => ResourceManager.GetString(nameof(Popup_PenTipByPointSet), _resourceCulture);

        public static string Popup_PenTipByVelocity => ResourceManager.GetString(nameof(Popup_PenTipByVelocity), _resourceCulture);

        public static string Popup_PenTipOff => ResourceManager.GetString(nameof(Popup_PenTipOff), _resourceCulture);

        public static string Popup_OverlapDarken => ResourceManager.GetString(nameof(Popup_OverlapDarken), _resourceCulture);

        public static string Popup_Transparent => ResourceManager.GetString(nameof(Popup_Transparent), _resourceCulture);

        public static string Popup_Delay => ResourceManager.GetString(nameof(Popup_Delay), _resourceCulture);

        public static string Popup_SpeedMultiplier => ResourceManager.GetString(nameof(Popup_SpeedMultiplier), _resourceCulture);

        public static string Popup_LightSeries => ResourceManager.GetString(nameof(Popup_LightSeries), _resourceCulture);

        public static string Popup_BgSettings => ResourceManager.GetString(nameof(Popup_BgSettings), _resourceCulture);

        public static string Popup_WhiteboardMode => ResourceManager.GetString(nameof(Popup_WhiteboardMode), _resourceCulture);

        public static string Popup_Blackboard => ResourceManager.GetString(nameof(Popup_Blackboard), _resourceCulture);

        public static string Popup_BgColor => ResourceManager.GetString(nameof(Popup_BgColor), _resourceCulture);

        public static string Popup_ApplyColor => ResourceManager.GetString(nameof(Popup_ApplyColor), _resourceCulture);
    }
}
