//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from SecurityStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class SecurityStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.SecurityStrings", typeof(SecurityStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string FileAssoc_Check => ResourceManager.GetString(nameof(FileAssoc_Check), _resourceCulture);

        public static string FileAssoc_Title => ResourceManager.GetString(nameof(FileAssoc_Title), _resourceCulture);

        public static string FileAssoc_Unregister => ResourceManager.GetString(nameof(FileAssoc_Unregister), _resourceCulture);

        public static string SecurityPanel__InkCanvasForClass_Hint => ResourceManager.GetString(nameof(SecurityPanel__InkCanvasForClass_Hint), _resourceCulture);

        public static string SecurityPanel__Settingsjson_Hint => ResourceManager.GetString(nameof(SecurityPanel__Settingsjson_Hint), _resourceCulture);

        public static string SecurityPanel_Hint => ResourceManager.GetString(nameof(SecurityPanel_Hint), _resourceCulture);

        public static string SecurityPanel_Hint_1 => ResourceManager.GetString(nameof(SecurityPanel_Hint_1), _resourceCulture);

        public static string SecurityPanel_Hint_2 => ResourceManager.GetString(nameof(SecurityPanel_Hint_2), _resourceCulture);

        public static string SecurityPanel_Hint_4 => ResourceManager.GetString(nameof(SecurityPanel_Hint_4), _resourceCulture);

        public static string Security_SectionPassword => ResourceManager.GetString(nameof(Security_SectionPassword), _resourceCulture);

        public static string Security_InfoBarTitle => ResourceManager.GetString(nameof(Security_InfoBarTitle), _resourceCulture);

        public static string Security_PasswordInfoBarMessage => ResourceManager.GetString(nameof(Security_PasswordInfoBarMessage), _resourceCulture);

        public static string Security_EnablePassword => ResourceManager.GetString(nameof(Security_EnablePassword), _resourceCulture);

        public static string Security_PasswordManagement => ResourceManager.GetString(nameof(Security_PasswordManagement), _resourceCulture);

        public static string Security_SetOrChangePassword => ResourceManager.GetString(nameof(Security_SetOrChangePassword), _resourceCulture);

        public static string Security_EnableTotp => ResourceManager.GetString(nameof(Security_EnableTotp), _resourceCulture);

        public static string Security_EnableTotpHint => ResourceManager.GetString(nameof(Security_EnableTotpHint), _resourceCulture);

        public static string Security_TotpSecretKey => ResourceManager.GetString(nameof(Security_TotpSecretKey), _resourceCulture);

        public static string Security_TotpSecretKeyHint => ResourceManager.GetString(nameof(Security_TotpSecretKeyHint), _resourceCulture);

        public static string Security_GenerateOrResetKey => ResourceManager.GetString(nameof(Security_GenerateOrResetKey), _resourceCulture);

        public static string Security_RequirePasswordOnExit => ResourceManager.GetString(nameof(Security_RequirePasswordOnExit), _resourceCulture);

        public static string Security_RequirePasswordOnEnterSettings => ResourceManager.GetString(nameof(Security_RequirePasswordOnEnterSettings), _resourceCulture);

        public static string Security_RequirePasswordOnResetConfig => ResourceManager.GetString(nameof(Security_RequirePasswordOnResetConfig), _resourceCulture);

        public static string Security_RequirePasswordOnModifyOrClearNameList => ResourceManager.GetString(nameof(Security_RequirePasswordOnModifyOrClearNameList), _resourceCulture);

        public static string Security_RequirePasswordOnModifyOrClearNameList_Hint => ResourceManager.GetString(nameof(Security_RequirePasswordOnModifyOrClearNameList_Hint), _resourceCulture);

        public static string Security_ProcessProtection => ResourceManager.GetString(nameof(Security_ProcessProtection), _resourceCulture);

        public static string Security_ProcessProtectionInfoBarMessage => ResourceManager.GetString(nameof(Security_ProcessProtectionInfoBarMessage), _resourceCulture);

        public static string Security_DisablePasswordTitle => ResourceManager.GetString(nameof(Security_DisablePasswordTitle), _resourceCulture);

        public static string Security_DisablePasswordMessage => ResourceManager.GetString(nameof(Security_DisablePasswordMessage), _resourceCulture);

        public static string Security_ResetTotpTitle => ResourceManager.GetString(nameof(Security_ResetTotpTitle), _resourceCulture);

        public static string Security_ResetTotpMessage => ResourceManager.GetString(nameof(Security_ResetTotpMessage), _resourceCulture);
    }
}