//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from TimerStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class TimerStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.TimerStrings", typeof(TimerStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Timer_CustomSoundLabel => ResourceManager.GetString(nameof(Timer_CustomSoundLabel), _resourceCulture);

        public static string Timer_EnableCountUp => ResourceManager.GetString(nameof(Timer_EnableCountUp), _resourceCulture);

        public static string Timer_NewUI => ResourceManager.GetString(nameof(Timer_NewUI), _resourceCulture);

        public static string Timer_OvertimeHighlight => ResourceManager.GetString(nameof(Timer_OvertimeHighlight), _resourceCulture);

        public static string Timer_Progressive => ResourceManager.GetString(nameof(Timer_Progressive), _resourceCulture);

        public static string Timer_ProgressiveCustomLabel => ResourceManager.GetString(nameof(Timer_ProgressiveCustomLabel), _resourceCulture);

        public static string Timer_ProgressiveSelectFile => ResourceManager.GetString(nameof(Timer_ProgressiveSelectFile), _resourceCulture);

        public static string Timer_ProgressiveVolume => ResourceManager.GetString(nameof(Timer_ProgressiveVolume), _resourceCulture);

        public static string Timer_Reset => ResourceManager.GetString(nameof(Timer_Reset), _resourceCulture);

        public static string Timer_Title => ResourceManager.GetString(nameof(Timer_Title), _resourceCulture);

        public static string Timer_UseLegacyButtons => ResourceManager.GetString(nameof(Timer_UseLegacyButtons), _resourceCulture);

        public static string Timer_Volume => ResourceManager.GetString(nameof(Timer_Volume), _resourceCulture);

        public static string Timer_HourUp => ResourceManager.GetString(nameof(Timer_HourUp), _resourceCulture);

        public static string Timer_HourDown => ResourceManager.GetString(nameof(Timer_HourDown), _resourceCulture);

        public static string Timer_HourDigitUp => ResourceManager.GetString(nameof(Timer_HourDigitUp), _resourceCulture);

        public static string Timer_HourDigitDown => ResourceManager.GetString(nameof(Timer_HourDigitDown), _resourceCulture);

        public static string Timer_MinuteUp => ResourceManager.GetString(nameof(Timer_MinuteUp), _resourceCulture);

        public static string Timer_MinuteDown => ResourceManager.GetString(nameof(Timer_MinuteDown), _resourceCulture);

        public static string Timer_MinuteDigitUp => ResourceManager.GetString(nameof(Timer_MinuteDigitUp), _resourceCulture);

        public static string Timer_MinuteDigitDown => ResourceManager.GetString(nameof(Timer_MinuteDigitDown), _resourceCulture);

        public static string Timer_SecondUp => ResourceManager.GetString(nameof(Timer_SecondUp), _resourceCulture);

        public static string Timer_SecondDown => ResourceManager.GetString(nameof(Timer_SecondDown), _resourceCulture);

        public static string Timer_SecondDigitUp => ResourceManager.GetString(nameof(Timer_SecondDigitUp), _resourceCulture);

        public static string Timer_SecondDigitDown => ResourceManager.GetString(nameof(Timer_SecondDigitDown), _resourceCulture);

        public static string Timer_CommonTab => ResourceManager.GetString(nameof(Timer_CommonTab), _resourceCulture);

        public static string Timer_RecentTab => ResourceManager.GetString(nameof(Timer_RecentTab), _resourceCulture);

        public static string Timer_45Minutes => ResourceManager.GetString(nameof(Timer_45Minutes), _resourceCulture);

        public static string Timer_FullScreen => ResourceManager.GetString(nameof(Timer_FullScreen), _resourceCulture);

        public static string Timer_StartPause => ResourceManager.GetString(nameof(Timer_StartPause), _resourceCulture);
    }
}