//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from WindowStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class WindowStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.WindowStrings", typeof(WindowStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Tray_ClickAction_CloseApp => ResourceManager.GetString(nameof(Tray_ClickAction_CloseApp), _resourceCulture);

        public static string Tray_ClickAction_DisableAllHotkeys => ResourceManager.GetString(nameof(Tray_ClickAction_DisableAllHotkeys), _resourceCulture);

        public static string Tray_ClickAction_ForceFullScreen => ResourceManager.GetString(nameof(Tray_ClickAction_ForceFullScreen), _resourceCulture);

        public static string Tray_ClickAction_HideShowMainWindow => ResourceManager.GetString(nameof(Tray_ClickAction_HideShowMainWindow), _resourceCulture);

        public static string Tray_ClickAction_NoAction => ResourceManager.GetString(nameof(Tray_ClickAction_NoAction), _resourceCulture);

        public static string Tray_ClickAction_OpenSettings => ResourceManager.GetString(nameof(Tray_ClickAction_OpenSettings), _resourceCulture);

        public static string Tray_ClickAction_ResetFloatingBarPosition => ResourceManager.GetString(nameof(Tray_ClickAction_ResetFloatingBarPosition), _resourceCulture);

        public static string Tray_ClickAction_RestartApp => ResourceManager.GetString(nameof(Tray_ClickAction_RestartApp), _resourceCulture);

        public static string Tray_ClickAction_ShowMenu => ResourceManager.GetString(nameof(Tray_ClickAction_ShowMenu), _resourceCulture);

        public static string Tray_ClickAction_TempShowMainWindow => ResourceManager.GetString(nameof(Tray_ClickAction_TempShowMainWindow), _resourceCulture);

        public static string Tray_ClickAction_ToggleFoldFloatingBar => ResourceManager.GetString(nameof(Tray_ClickAction_ToggleFoldFloatingBar), _resourceCulture);

        public static string Tray_EnableTrayIcon => ResourceManager.GetString(nameof(Tray_EnableTrayIcon), _resourceCulture);

        public static string Tray_GroupTitle => ResourceManager.GetString(nameof(Tray_GroupTitle), _resourceCulture);

        public static string Tray_LeftClickAction => ResourceManager.GetString(nameof(Tray_LeftClickAction), _resourceCulture);

        public static string Tray_RightClickAction => ResourceManager.GetString(nameof(Tray_RightClickAction), _resourceCulture);

        public static string Window_WindowChromeRendering => ResourceManager.GetString(nameof(Window_WindowChromeRendering), _resourceCulture);

        public static string Window_WindowChromeRendering_RestartRequired => ResourceManager.GetString(nameof(Window_WindowChromeRendering_RestartRequired), _resourceCulture);

        public static string Window_WindowChromeRenderingHint => ResourceManager.GetString(nameof(Window_WindowChromeRenderingHint), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);

        public static string WindowSettings => ResourceManager.GetString(nameof(WindowSettings), _resourceCulture);

        public static string MultiScreenSupport => ResourceManager.GetString(nameof(MultiScreenSupport), _resourceCulture);

        public static string MultiScreenSupportHint => ResourceManager.GetString(nameof(MultiScreenSupportHint), _resourceCulture);

        public static string FollowMouseScreen => ResourceManager.GetString(nameof(FollowMouseScreen), _resourceCulture);

        public static string FollowMouseScreenHint => ResourceManager.GetString(nameof(FollowMouseScreenHint), _resourceCulture);
    }
}